{
	"next_topic_id": 1,
	"topic": [],
	"topic_vote": {},
	"next_comment_id": 2,
	"comment": {
		"5_1M1c7x7SLau8D2bm8Gw8iWQbBqe9X4zqPw": [
			{
				"comment_id": 1,
				"body": "I get this error:\n\n- Starting ZeroNet...\n[12:01:29] - OpenSSL loaded, version: 01000201F\n[12:01:30] - Patching sockets to tor socks proxy: 127.0.0.1:9050\n[12:01:30] - Version: 0.3.7 r1287, Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)], Gevent: 1.0.1\n[12:01:31] - Creating FileServer....\n[12:01:32] - Unhandled exception\nNone\nTraceback (most recent call last):\n  File \"_ctypes/callbacks.c\", line 314, in 'calling callback function'\n  File \"plugins\\Trayicon\\lib\\notificationicon.py\", line 734, in _callback\n    self._menu()\n  File \"plugins\\Trayicon\\lib\\notificationicon.py\", line 681, in _menu\n    itemstring = fs[0]()\n  File \"plugins\\Trayicon\\TrayiconPlugin.py\", line 78, in titleIp\n    if self.main.file_server.port_opened:\nAttributeError: 'module' object has no attribute 'file_server'\n[12:01:32] TorManager Tor controller connect error: error: [Errno 10061] No connection could be made because the target machine actively refused it. in TorManager.py line 154 > socket.py line 342\n[12:01:32] - Creating UiServer....\n[12:01:32] Site:1Name2..hM9F Content.json not exist: data/1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F/content.json\n[12:01:32] - Removing old SSL certs...\n[12:01:32] - Starting servers....\n[12:01:32] TorManager Downloading Tor...\n[12:01:33] Ui.UiServer --------------------------------------\n[12:01:33] Ui.UiServer Web interface: http://127.0.0.1:43110/\n[12:01:33] Ui.UiServer --------------------------------------\n[12:01:33] - Failed to modify max files open limit: No module named win32file\n[12:01:37] Site:1Name2..hM9F Content.json not exist: data/1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F/content.json\n[12:01:38] FileServer Checking port 15441 using portchecker.co...\n[12:01:38] TorManager Error starting Tor client: ProxyConnectionError: Error connecting to SOCKS5 proxy 127.0.0.1:49050: [Errno 10061] No connection could be made because the target machine actively refused it. in TorManager.py line 74 > TorManager.py line 101 > helper.py line 130 > SocksProxy.py line 12 > socks.py line 674\n[12:01:38] Site:1Name2..hM9F Announce to 0 trackers in 1.032s, failed\n[12:02:19] Site:1Name2..hM9F Announce to 0 trackers in 1.004s, failed\n[12:03:30] FileServer Internet offline\n[12:03:46] Site:1Name2..hM9F Announce to 0 trackers in 1.017s, failed\n[12:04:21] Site:1Name2..hM9F Announce to 0 trackers in 1.015s, failed\n\n\nMy torrc file:\n\n# Tor config for ZeroNet\n\nDataDirectory data\nDirReqStatistics 0\nGeoIPFile geoip\\geoip\nGeoIPv6File geoip\\geoip6\n\n# Log notice file data\\notice.log\n\nControlPort 49051\nSOCKSPort 49050\n\nCookieAuthentication 1\n\nClientTransportPlugin fte exec data\\PluggableTransports\\fteproxy --managed\nClientTransportPlugin obfs2,obfs3,obfs4,scramblesuit exec data\\PluggableTransports\\obfs4proxy\n\nUseBridges 1\nBridge xxx.xxx.xxx.xxx:xxxx 63ddf8cd106a95fs07efe538eFAKe7a6f92d28f94\nBridge xxx.xxx.xxx.xxx:xxxx 63ddf8cd106a95fs07efe538eFAKe7a6f92d28f94\nBridge xxx.xxx.xxx.xxx:xxxx 63ddf8cd106a95fs07efe538eFAKe7a6f92d28f94\nBridge xxx.xxx.xxx.xxx:xxxx 63ddf8cd106a95fs07efe538eFAKe7a6f92d28f94\nBridge xxx.xxx.xxx.xxx:xxxx 63ddf8cd106a95fs07efe538eFAKe7a6f92d28f94\nBridge xxx.xxx.xxx.xxx:xxxx 63ddf8cd106a95fs07efe538eFAKe7a6f92d28f94\nBridge xxx.xxx.xxx.xxx:xxxx 63ddf8cd106a95fs07efe538eFAKe7a6f92d28f94\nBridge xxx.xxx.xxx.xxx:xxxx 63ddf8cd106a95fs07efe538eFAKe7a6f92d28f94\nBridge xxx.xxx.xxx.xxx:xxxx 63ddf8cd106a95fs07efe538eFAKe7a6f92d28f94\nBridge xxx.xxx.xxx.xxx:xxxx 63ddf8cd106a95fs07efe538eFAKe7a6f92d28f94\nBridge xxx.xxx.xxx.xxx:xxxx 63ddf8cd106a95fs07efe538eFAKe7a6f92d28f94\nBridge xxx.xxx.xxx.xxx:xxxx 63ddf8cd106a95fs07efe538eFAKe7a6f92d28f94\n\nHiddenServiceStatistics 0\n\nHTTPProxy xxx.xxx.xxx.xxx:8080",
				"added": 1465869898
			}
		]
	},
	"comment_vote": {
		"2_1JuFwBugxhHoKv9sLTHcutiUPtofM5169n": 1
	}
}