{"cert_user_id": "rubo77@github", "next_comment_id": 8, "comment": {"1604066124_mirrored_tianlichunhong_github": [{"comment_id": 1, "body": "dependencies are msgpack-python python-gevent", "added": 1530376187, "modified": 1530376187, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1106#issuecomment-401561457", "source_type": "github"}], "1604067608_mirrored_ZeroNetTickBot_github": [{"comment_id": 2, "body": "GPLv3 and Lax", "added": 1572873162, "modified": 1572873162, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2273#issuecomment-549426603", "source_type": "github"}], "1604067875_mirrored_rubo77_github": [{"comment_id": 3, "body": "This made it work, that it installs, but the docker container is restarting every minute now:\r\n\r\n    6b6e0937b8f8        nofish/zeronet      \"sh -c ' ( [ -e /roo\u2026\"   15 minutes ago      Restarting (1) 5 seconds ago    proxy.zites.cf\r\n\r\n`docker logs  proxy.zites.cf` sais:\r\n\r\n```\r\n       \r\n[16:21:06] ConnServer Server port opened ipv4: False, ipv6: None      \r\n[16:21:49] - Shutting down (reason: SIGTERM)...                           \r\n[16:21:49] - All server stopped                                   ", "added": 1585402624, "modified": 1585402844, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2500#issuecomment-605485799", "source_type": "github"}, {"comment_id": 4, "body": "If I remove the last line `command: \"sh -c ' ( [ -e /root/...` then the docker runs fine and I can reach zeronet locally by http://0.0.0.0:43110\r\n\r\nNow I only have to figure out, how to allow nginx to proxy it to the outside. Other docker services I can just proxy out by configuring the port, docker serves its service to the VM, but it doesn_t work on my zeronet.\r\n\r\nIs there a special option, that I have to enable for this?", "added": 1585474996, "modified": 1585474996, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2500#issuecomment-605630218", "source_type": "github"}, {"comment_id": 5, "body": "The docker container runs fine, and I can connect to it locally via \r\n\r\n    w3m http://127.0.0.1:43110\r\n\r\n\r\nI tried to add a zeronet.conf file, but It complained, that it must be a directory:\r\n\r\n    ERROR: for zeronet_zeronet_1  Cannot start service zeronet: OCI runtime create failed: container_linux.go:349: starting container process caused \"process_linux.go:449: container init caused \\\"rootfs_linux.go:58: mounting \\\\\\\"/var/kunden/docker-services/zeronet/zeronet.conf\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/devicemapper/mnt/ebfe2a34e40cd9a614f576aeafd2caa7ab1ace015375f213eef57373cdb1d995/rootfs\\\\\\\" at \\\\\\\"/var/lib/docker/devicemapper/mnt/ebfe2a34e40cd9a614f576aeafd2caa7ab1ace015375f213eef57373cdb1d995/rootfs/root/zeronet.conf\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type\r\n\r\n\r\nso I added `zeronet.conf/zeronet.conf`\r\n\r\n```\r\n[global]\r\nui_ip = '*'\r\n```\r\n\r\nBut still I cannot reach it from outside the VM not even via the main IP of the VM:\r\n\r\n     w3m http://10.77.77.106:43110", "added": 1588457315, "modified": 1588457912, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2500#issuecomment-623037222", "source_type": "github"}, {"comment_id": 6, "body": "It seems like in your docker-image, there is a folder already at /root/zeronet.conf/ which prevents mounting of a file there", "added": 1588459293, "modified": 1588459293, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2500#issuecomment-623040326", "source_type": "github"}, {"comment_id": 7, "body": "Docker Supports mounting files, it should work with the path before the filename like I did", "added": 1588612599, "modified": 1588612599, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2500#issuecomment-623682540", "source_type": "github"}]}, "next_topic_id": 3, "topic": [{"topic_id": 1604066591, "title": "de.json - correct german translation", "body": "", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1530636147, "modified": 1530645569, "source_link": "https://github.com/HelloZeroNet/ZeroNet/pull/1473", "source_type": "github"}, {"topic_id": 1604067875, "title": "python not found during docker-compose up", "body": "I tried to start a zeronode with this docker-compose.yml file, I found [here](https://github.com/HelloZeroNet/ZeroNet/issues/1904#issuecomment-464748094):\r\n```\r\nversion: '3'\r\nservices:\r\n\r\n  proxy:\r\n    container_name: proxy.zites.cf\r\n    image: nofish/zeronet\r\n    restart: always\r\n    environment:\r\n      ENABLE_TOR: \"true\"\r\n    volumes:\r\n      - ./data:/root/data\r\n      - ./log:/root/log\r\n      - ./zeronet.conf:/root/zeronet.conf\r\n    ports:\r\n      - \"26552:26552\"\r\n      - \"127.0.0.1:43110:43110\"\r\n    command: \"sh -c ' ( [ -e /root/plugins/disabled-Multiuser ] && rm -rf /root/plugins/Multiuser && mv /root/plugins/disabled-Multiuser /root/plugins/Multiuser ) && (/usr/bin/tor &) && python zeronet.py --ui_host proxy.zites.cf 127.0.0.1:43110 --ui_ip 0.0.0.0 --fileserver_port 26552'\"\r\n\r\n```\r\nbut when I run \r\n\r\n    docker-compose up\r\n\r\nIt exits with an error:\r\n\r\n```\r\n\r\nCreating network \"zeronet_default\" with the default driver\r\nPulling proxy (nofish/zeronet:)...\r\nlatest: Pulling from nofish/zeronet\r\naad63a933944: Pull complete\r\n01a00972849f: Pull complete\r\n9bddbe39f010: Pull complete\r\nea7ed6b444e6: Pull complete\r\nDigest: sha256:19aac3fbb8dd7eedf05423e7c6f69a2090a5ee85f21ff6cc50d2e425b469a777\r\nStatus: Downloaded newer image for nofish/zeronet:latest\r\nCreating proxy.zites.cf ... done\r\nAttaching to proxy.zites.cf\r\nproxy.zites.cf | sh: python: not found\r\nproxy.zites.cf exited with code 1\r\n", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1585400856, "modified": 1588612599, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2500", "source_type": "github"}]}