{"cert_user_id": "CPCer@github", "next_comment_id": 5, "comment": {"1604065406_mirrored_zerotrix_github": [{"comment_id": 1, "body": "same problem here... someone suggest me using .exe version on my win8. Seemed fine now  #770 ", "added": 1484531877, "modified": 1484531877, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/532#issuecomment-272774162", "source_type": "github"}], "1604065479_mirrored_dnelband_github": [{"comment_id": 2, "body": "@ysc3839 @HelloZeroNet when i'm deleting sites this appeared again\r\n`Internal error: KeyError: u'data/users/{user_adress}/content.json'\r\nUiWebsocket.py line 105 > UiWebsocket.py line 200 > UiWebsocket.py line 726 > Site.py line 1006 > SiteStorage.py line 392 > ContentDbDict.py line 55 > ContentDbDict.py line 28`\r\nand i cannnot find folders related with \"{user_adress}\" or sites in sites.json....", "added": 1487666147, "modified": 1491540582, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/586#issuecomment-281318497", "source_type": "github"}], "1604065704_mirrored_CPCer_github": [{"comment_id": 3, "body": "@ysc3839 thank you!\r\n i did run it in cmd and the force close still appeared...\r\nthen i add a pause and run as administrator\r\n![1](https://cloud.githubusercontent.com/assets/8787958/21971464/caeb4ee6-dbeb-11e6-9721-31bbc6f71d01.png)\r\nalso getting permission denied on browsers. like this one #532 \r\n\r\n**However, the exe version works fine till now.**\r\n\r\nSo, Thanks again. ", "added": 1484532145, "modified": 1484534719, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/770#issuecomment-272774541", "source_type": "github"}, {"comment_id": 4, "body": "After I inserted \"import os\" and \"os.system(\"pause\") \" in start.py, it won't force close\r\n\r\nbut still get a ERR_CONNECTION_REFUSED in Chrome\r\n\r\n```[13:34:22] - OpenSSL loaded, version: 01000201F\r\n[13:34:22] - Version: 0.5.1 r1795, Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2\r\n016, 15:19:22) [MSC v.1500 32 bit (Intel)], Gevent: 1.1.2\r\n[13:34:22] - Creating FileServer....\r\n[13:34:23] TorManager Tor controller connect error: error: [Errno 10061] [Error\r\n10061] No connection could be made because the target machine actively refused i\r\nt. in TorManager.py line 157 > socket2.py line 228\r\n[13:34:23] TorManager Starting Tor client tools/tor/tor.exe...\r\nJan 16 13:34:24.375 [notice] Tor v0.2.8.11 (git-31e7b47fbebe8caf) running on Win\r\ndows 8 with Libevent 2.0.22-stable, OpenSSL 1.0.1u and Zlib 1.2.8.\r\nJan 16 13:34:24.375 [notice] Tor can't help you if you use it wrong! Learn how t\r\no be safe at https://www.torproject.org/download/download#warning\r\nJan 16 13:34:24.391 [notice] Read configuration file \"\u00d7\u00d7\u00d7\\ZeroBundle\r\nZeroNet\\tools\\tor\\torrc\".\r\nJan 16 13:34:24.391 [warn] Path for GeoIPFile (geoip\\geoip) is relative and will\r\nresolve to \u00d7\u00d7\u00d7\\ZeroBundle\\ZeroNet\\tools\\tor\\geoip\\geoip. Is this wha\r\nt you wanted?\r\nJan 16 13:34:24.391 [warn] Path for GeoIPv6File (geoip\\geoip6) is relative and w\r\nill resolve to \u00d7\u00d7\u00d7\\ZeroBundle\\ZeroNet\\tools\\tor\\geoip\\geoip6. Is this\r\nwhat you wanted?\r\nJan 16 13:34:24.391 [warn] Path for DataDirectory (data) is relative and will re\r\nsolve to \u00d7\u00d7\u00d7\\ZeroBundle\\ZeroNet\\tools\\tor\\data. Is this what you want\r\ned?\r\nJan 16 13:34:24.407 [notice] Opening Socks listener on 127.0.0.1:49050\r\nJan 16 13:34:24.407 [notice] Opening Control listener on 127.0.0.1:49051\r\nJan 16 13:34:24.000 [notice] Bootstrapped 0%: Starting\r\nJan 16 13:34:25.000 [notice] Bootstrapped 80%: Connecting to the Tor network\r\nJan 16 13:34:25.000 [notice] New control connection opened from 127.0.0.1.\r\n[13:34:25] - Creating UiServer....\r\nTraceback (most recent call last):\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\ZeroNet\\zeronet.py\", line 18, in main\r\nmain.start()\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\ZeroNet\\src\\main.py\", line 450, in start\r\nactions.call(config.action, action_kwargs)\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\ZeroNet\\src\\main.py\", line 129, in call\r\nfunc(**kwargs)\r\nFile \"plugins\\Trayicon\\TrayiconPlugin.py\", line 65, in main\r\nsuper(ActionsPlugin, self).main()\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\ZeroNet\\src\\main.py\", line 139, in main\r\nui_server = UiServer()\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\ZeroNet\\src\\Ui\\UiServer.py\", line 61, in ini\r\nt\r\nself.sites = SiteManager.site_manager.list()\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\ZeroNet\\src\\Site\\SiteManager.py\", line 146, in\r\nlist\r\nself.load()\r\nFile \"plugins\\Zeroname\\SiteManagerPlugin.py\", line 20, in load\r\nsuper(SiteManagerPlugin, self).load(*args, **kwargs)\r\nFile \"plugins\\MergerSite\\MergerSitePlugin.py\", line 333, in load\r\nself.updateMergerSites()\r\nFile \"plugins\\MergerSite\\MergerSitePlugin.py\", line 301, in updateMergerSites\r\nmerged_type = site.content_manager.contents.get(\"content.json\", {}).get(\"mer\r\nged_type\")\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\ZeroNet\\src\\Content\\ContentDbDict.py\", line 10\r\n5, in get\r\nreturn self.getitem(key)\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\ZeroNet\\src\\Content\\ContentDbDict.py\", line 55\r\n, in getitem\r\nreturn self.loadItem(key)\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\ZeroNet\\src\\Content\\ContentDbDict.py\", line 23\r\n, in loadItem\r\ncontent = self.site.storage.loadJson(key)\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\ZeroNet\\src\\Site\\SiteStorage.py\", line 231, in\r\nloadJson\r\nreturn json.load(file)\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\Python\\lib\\json_init.py\", line 291, in loa\r\nd\r\n**kw)\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\Python\\lib\\json_init_.py\", line 339, in loa\r\nds\r\nreturn _default_decoder.decode(s)\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\Python\\lib\\json\\decoder.py\", line 364, in deco\r\nde\r\nobj, end = self.raw_decode(s, idx=w(s, 0).end())\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\Python\\lib\\json\\decoder.py\", line 382, in raw\r\ndecode\r\nraise ValueError(\"No JSON object could be decoded\")\r\nValueError: No JSON object could be decoded\r\nPress any key to continue . . . Jan 16 13:34:27.000 [notice] Bootstrapped 85%: F\r\ninishing handshake with first hop\r\nJan 16 13:34:28.000 [notice] Bootstrapped 90%: Establishing a Tor circuit\r\nJan 16 13:34:29.000 [notice] Tor has successfully opened a circuit. Looks like c\r\nlient functionality is working.\r\nJan 16 13:34:29.000 [notice] Bootstrapped 100%: Done\r\n\r\nError in atexit.run_exitfuncs:\r\nTraceback (most recent call last):\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\Python\\lib\\atexit.py\", line 24, in run_exitfu\r\nncs\r\nfunc(*targs, **kargs)\r\nFile \"plugins\\MergerSite\\MergerSitePlugin.py\", line 337, in save\r\nself.updateMergerSites()\r\nFile \"plugins\\MergerSite\\MergerSitePlugin.py\", line 301, in updateMergerSites\r\nmerged_type = site.content_manager.contents.get(\"content.json\", {}).get(\"mer\r\nged_type\")\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\ZeroNet\\src\\Content\\ContentDbDict.py\", line 10\r\n5, in get\r\nreturn self.getitem(key)\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\ZeroNet\\src\\Content\\ContentDbDict.py\", line 55\r\n, in getitem\r\nreturn self.loadItem(key)\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\ZeroNet\\src\\Content\\ContentDbDict.py\", line 23\r\n, in loadItem\r\ncontent = self.site.storage.loadJson(key)\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\ZeroNet\\src\\Site\\SiteStorage.py\", line 231, in\r\nloadJson\r\nreturn json.load(file)\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\Python\\lib\\json_init.py\", line 291, in loa\r\nd\r\n**kw)\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\Python\\lib\\json_init.py\", line 339, in loa\r\nds\r\nreturn default_decoder.decode(s)\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\Python\\lib\\json\\decoder.py\", line 364, in deco\r\nde\r\nobj, end = self.raw_decode(s, idx=w(s, 0).end())\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\Python\\lib\\json\\decoder.py\", line 382, in raw\r\ndecode\r\nraise ValueError(\"No JSON object could be decoded\")\r\nValueError: No JSON object could be decoded\r\nIcon thread stopped, removing icon...\r\nError in sys.exitfunc:\r\n[13:37:35] - Unhandled exception\r\nNone\r\nTraceback (most recent call last):\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\Python\\lib\\atexit.py\", line 24, in run_exitfu\r\nncs\r\nfunc(*targs, **kargs)\r\nFile \"plugins\\MergerSite\\MergerSitePlugin.py\", line 337, in save\r\nself.updateMergerSites()\r\nFile \"plugins\\MergerSite\\MergerSitePlugin.py\", line 301, in updateMergerSites\r\nmerged_type = site.content_manager.contents.get(\"content.json\", {}).get(\"mer\r\nged_type\")\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\ZeroNet\\src\\Content\\ContentDbDict.py\", line 10\r\n5, in get\r\nreturn self.getitem(key)\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\ZeroNet\\src\\Content\\ContentDbDict.py\", line 55\r\n, in getitem\r\nreturn self.loadItem(key)\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\ZeroNet\\src\\Content\\ContentDbDict.py\", line 23\r\n, in loadItem\r\ncontent = self.site.storage.loadJson(key)\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\ZeroNet\\src\\Site\\SiteStorage.py\", line 231, in\r\nloadJson\r\nreturn json.load(file)\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\Python\\lib\\json_init.py\", line 291, in loa\r\nd\r\n**kw)\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\Python\\lib\\json_init.py\", line 339, in loa\r\nds\r\nreturn _default_decoder.decode(s)\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\Python\\lib\\json\\decoder.py\", line 364, in deco\r\nde\r\nobj, end = self.raw_decode(s, idx=w(s, 0).end())\r\nFile \"\u00d7\u00d7\u00d7\\ZeroBundle\\Python\\lib\\json\\decoder.py\", line 382, in raw\r\ndecode\r\nraise ValueError(\"No JSON object could be decoded\")\r\nValueError: No JSON object could be decoded\r\n\r\n\u00d7\u00d7\u00d7\\ZeroBundle\\ZeroNet>pause\r\nPress any key to continue . . .```", "added": 1484534640, "modified": 1484548671, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/770#issuecomment-272778508", "source_type": "github"}]}, "next_topic_id": 2, "topic": [{"topic_id": 1604065704, "title": "force close with nothing showed", "body": "win8 newest ZeroNet (I guess)\r\nwhether i opened start.cmd or zeronet.cmd, it flashed and then closed...\r\nit works okay days ago...\r\nAnd here's what i can capture...\r\n![image](https://cloud.githubusercontent.com/assets/8787958/21963400/ea4765a8-db74-11e6-87e2-4d560e62a06c.png)\r\n\r\n", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1484481059, "modified": 1588049594, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/770", "source_type": "github"}]}