{"cert_user_id": "chenxuuu@github", "next_topic_id": 2, "topic": [{"topic_id": 1604067507, "title": "start fail on Raspberry Pi", "body": "### Step 1: Please describe your environment\r\n\r\n  * ZeroNet version: latest\r\n  * Operating system: Linux raspberrypi 4.14.50-v7+ #1122 SMP Tue Jun 19 12:26:26 BST 2018 armv7l GNU/Linux\r\n  * Web browser: none\r\n  * Tor status: not available\r\n  * Opened port: no\r\n  * Special configuration: none\r\n\r\n### Step 2: Describe the problem:\r\n\r\n#### Steps to reproduce:\r\n\r\nwget https://github.com/HelloZeroNet/ZeroNet/archive/py3/ZeroNet-py3.tar.gz\r\ntar xvpfz ZeroNet-py3.tar.gz\r\ncd ZeroNet-py3\r\nsudo python3.7 -m pip install -r requirements.txt\r\npython3.7 zeronet.py\r\n\r\n#### Observed Results:\r\n\r\n```bash\r\npi@raspberrypi:~/hd/zeronet/ZeroNet-py3 $ python3.7 zeronet.py\r\n- Starting ZeroNet...\r\n[14:36:49] - Unhandled exception: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/lib/python3.7/site-packages/gevent/libuv/_corecffi.abi3.so)\r\nTraceback (most recent call last):\r\n  File \"zeronet.py\", line 16, in main\r\n    import main\r\n  File \"/home/pi/hd/zeronet/ZeroNet-py3/src/main.py\", line 59, in <module>\r\n    from Debug import DebugHook\r\n  File \"/home/pi/hd/zeronet/ZeroNet-py3/src/Debug/DebugHook.py\", line 10, in <module>\r\n    from . import Debug\r\n  File \"/home/pi/hd/zeronet/ZeroNet-py3/src/Debug/Debug.py\", line 77, in <module>\r\n    gevent.spawn(testBlock)\r\n  File \"src/gevent/greenlet.py\", line 588, in gevent._greenlet.Greenlet.spawn\r\n  File \"src/gevent/greenlet.py\", line 213, in gevent._greenlet.Greenlet.__init__\r\n  File \"src/gevent/_hub_local.py\", line 80, in gevent.__hub_local.get_hub_noargs\r\n  File \"/usr/local/lib/python3.7/site-packages/gevent/hub.py\", line 414, in __init__\r\n    self.loop = self.loop_class(flags=loop, default=default) # pylint:disable=not-callable\r\n  File \"/usr/local/lib/python3.7/site-packages/gevent/hub.py\", line 428, in loop_class\r\n    return GEVENT_CONFIG.loop\r\n  File \"/usr/local/lib/python3.7/site-packages/gevent/_config.py\", line 50, in getter\r\n    return self.settings[setting_name].get()\r\n  File \"/usr/local/lib/python3.7/site-packages/gevent/_config.py\", line 146, in get\r\n    self.value = self.validate(self._default())\r\n  File \"/usr/local/lib/python3.7/site-packages/gevent/_config.py\", line 248, in validate\r\n    return self._import_one_of([self.shortname_map.get(x, x) for x in value])\r\n  File \"/usr/local/lib/python3.7/site-packages/gevent/_config.py\", line 223, in _import_one_of\r\n    return self._import_one(candidates[-1])\r\n  File \"/usr/local/lib/python3.7/site-packages/gevent/_config.py\", line 237, in _import_one\r\n    module = importlib.import_module(module)\r\n  File \"/usr/local/lib/python3.7/importlib/__init__.py\", line 127, in import_module\r\n    return _bootstrap._gcd_import(name[level:], package, level)\r\n  File \"/usr/local/lib/python3.7/site-packages/gevent/libuv/loop.py\", line 15, in <module>\r\n    from gevent.libuv import _corecffi # pylint:disable=no-name-in-module,import-error\r\nImportError: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/lib/python3.7/site-packages/gevent/libuv/_corecffi.abi3.so)\r\n---\r\nPlease report it: https://github.com/HelloZeroNet/ZeroNet/issues/new?assignees=&labels=&template=bug-report.md\r\n```\r\n\r\n#### Expected Results:\r\n\r\nshould be started, but not\r\n", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1568518844, "modified": 1575853006, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2195", "source_type": "github"}], "next_comment_id": 6, "comment": {"1604067507_mirrored_chenxuuu_github": [{"comment_id": 1, "body": "@imachug  thanks, I try this, but still error with it", "added": 1568524254, "modified": 1568524254, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2195#issuecomment-531544702", "source_type": "github"}, {"comment_id": 2, "body": "@HelloZeroNet \r\n`ldd (Debian GLIBC 2.24-11+deb9u3) 2.24`\r\nversion is too old?", "added": 1568598188, "modified": 1568598188, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2195#issuecomment-531639105", "source_type": "github"}, {"comment_id": 3, "body": "> \r\n> \r\n> Whats your `ldd --version`?\r\n> \r\n> you can try `sudo python3.7 -m pip remove gevent`\r\n> `sudo apt install python3-gevent`\r\n\r\nmy python3.7 was installed by compiling source code, should I recompile this?", "added": 1568779754, "modified": 1568779754, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2195#issuecomment-532551514", "source_type": "github"}, {"comment_id": 4, "body": "my python3.7 was compiled from source code\r\nI'll try reinstall from apt", "added": 1575583948, "modified": 1575583948, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2195#issuecomment-562388820", "source_type": "github"}, {"comment_id": 5, "body": " I reinstall python from apt, it works\r\nthanks for everyone!", "added": 1575853005, "modified": 1575853005, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2195#issuecomment-563052370", "source_type": "github"}]}}