{"cert_user_id": "shitface666@github", "next_topic_id": 2, "topic": [{"topic_id": 1604066121, "title": "cant create a site in LinuxOS64bit ZeroNet.py siteCreate", "body": "./zeronet.py siteCreate\r\n\r\n- Starting ZeroNet...\r\nERROR:root:Unhandled exception: No module named gevent\r\nTraceback (most recent call last):\r\n  File \"./zeronet.py\", line 18, in main\r\n    import main\r\n  File \"/home/myfilepath/\", line 9, in <module>\r\n    import gevent\r\nImportError: No module named gevent\r\nTraceback (most recent call last):\r\n  File \"./zeronet.py\", line 91, in <module>\r\n    main()\r\n  File \"./zeronet.py\", line 64, in main\r\n    traceback.print_exc(file=open(config.log_dir + \"/error.log\", \"a\"))\r\nAttributeError: 'Config' object has no attribute 'log_dir'\r\n\r\nwhat i did was\r\nsu\r\n1.chmod +x zeronet.py\r\n2.chmod +x main.py\r\n\r\ni run ZeroNet.sh in root when i first try it\r\n\r\nnot in root\r\nbash zeronet.py siteCreate\r\nzeronet.py: line 8: syntax error near unexpected token `('\r\nzeronet.py: line 8: `def main():'\r\n", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1504187938, "modified": 1507827510, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1104", "source_type": "github"}]}