{"cert_user_id": "keith24@github", "next_comment_id": 2, "comment": {"1604064877_mirrored_HelloZeroNet_github": [{"comment_id": 1, "body": "I am getting\r\n\r\n    zeronet.py: error: unrecognized arguments: --ui_password mypassword\r\n\r\nwith v0.5.4.  Should I start a new issue or am I doing it wrong?  ", "added": 1493475417, "modified": 1493475417, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/91#issuecomment-298181890", "source_type": "github"}]}}