{"cert_user_id": "jamesalexanderdickerson@github", "next_topic_id": 2, "topic": [{"topic_id": 1604065156, "title": "Getting error whenever I open ZeroNet.app on OSX", "body": "Server error\nErr: Exception: File not allowed: data/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/index.html in UiServer.py line 81 > UiRequest.py line 82 > UiRequest.py line 211 > UiRequest.py line 285 > SiteStorage.py line 230 > SiteStorage.py line 250\nPlease report it if you think this an error.\nDetails:\n\n{\n    \"GATEWAY_INTERFACE\": \"CGI/1.1\", \n    \"HTTP_ACCEPT\": \"text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8\", \n    \"HTTP_ACCEPT_ENCODING\": \"gzip, deflate\", \n    \"HTTP_ACCEPT_LANGUAGE\": \"en-US,en;q=0.5\", \n    \"HTTP_CONNECTION\": \"keep-alive\", \n    \"HTTP_HOST\": \"127.0.0.1:43110\", \n    \"HTTP_USER_AGENT\": \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:44.0) Gecko/20100101 Firefox/44.0\", \n    \"PATH_INFO\": \"/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D\", \n    \"QUERY_STRING\": \"\", \n    \"REMOTE_ADDR\": \"127.0.0.1\", \n    \"REMOTE_PORT\": \"57155\", \n    \"REQUEST_METHOD\": \"GET\", \n    \"SCRIPT_NAME\": \"\", \n    \"SERVER_NAME\": \"1.0.0.127.in-addr.arpa\", \n    \"SERVER_PORT\": \"43110\", \n    \"SERVER_PROTOCOL\": \"HTTP/1.1\", \n    \"SERVER_SOFTWARE\": \"gevent/1.0 Python/2.7\", \n    \"arguments\": {\n        \"action\": \"main\", \n        \"batch\": false, \n        \"coffeescript_compiler\": null, \n        \"config_file\": \"zeronet.conf\", \n        \"connected_limit\": 15, \n        \"data_dir\": \"data\", \n        \"debug\": false, \n        \"debug_socket\": false, \n        \"disable_encryption\": false, \n        \"disable_sslcompression\": true, \n        \"disable_udp\": false, \n        \"fileserver_ip\": \"*\", \n        \"fileserver_port\": 15441, \n        \"homepage\": \"1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D\", \n        \"ip_external\": null, \n        \"keep_ssl_cert\": false, \n        \"log_dir\": \"log\", \n        \"max_files_opened\": 1024, \n        \"msgpack_purepython\": true, \n        \"open_browser\": \"default_browser\", \n        \"proxy\": null, \n        \"size_limit\": 10, \n        \"stream_downloads\": false, \n        \"tor\": \"enable\", \n        \"tor_controller\": \"127.0.0.1:9051\", \n        \"tor_proxy\": \"127.0.0.1:9050\", \n        \"trackers\": [\n            \"zero://boot3rdez4rzn36x.onion:15441\", \n            \"zero://boot.zeronet.io#f36ca555bee6ba216b14d10f38c16f7769ff064e0e37d887603548cc2e64191d:15441\", \n            \"udp://tracker.coppersurfer.tk:6969\", \n            \"udp://tracker.leechers-paradise.org:6969\", \n            \"udp://9.rarbg.com:2710\", \n            \"http://tracker.aletorrenty.pl:2710/announce\", \n            \"http://explodie.org:6969/announce\", \n            \"http://torrent.gresille.org/announce\"\n        ], \n        \"trackers_file\": false, \n        \"ui_ip\": \"127.0.0.1\", \n        \"ui_port\": 43110, \n        \"ui_restrict\": false, \n        \"use_openssl\": true, \n        \"use_tempfiles\": false, \n        \"verbose\": false\n    }, \n    \"plugins\": [\n        \"AnnounceZero\", \n        \"CryptMessage\", \n        \"Newsfeed\", \n        \"Sidebar\", \n        \"Stats\", \n        \"Trayicon\", \n        \"Zeroname\"\n    ], \n    \"version_gevent\": \"1.0.2\", \n    \"version_python\": \"2.7.11 |Anaconda 2.5.0 (x86_64)| (default, Dec  6 2015, 18:57:58) \\n[GCC 4.2.1 (Apple Inc. build 5577)]\", \n    \"version_zeronet\": \"0.3.6 r948\", \n    \"wsgi.url_scheme\": \"http\"\n}\n", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1457334432, "modified": 1457817290, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/336", "source_type": "github"}], "next_comment_id": 4, "comment": {"1604065156_mirrored_jamesalexanderdickerson_github": [{"comment_id": 1, "body": "Yes, both URLs get the same error. Also the same error in both Firefox and Chrome.\n", "added": 1457483169, "modified": 1457483169, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/336#issuecomment-194096877", "source_type": "github"}, {"comment_id": 2, "body": "No special characters. It was first extracted to my Downloads folder. I also tried moving it to my Applications folder. The very first time I ran the application, it appeared to work, and then every time after, I get the error, no matter where it's located.\n", "added": 1457582717, "modified": 1457582717, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/336#issuecomment-194707486", "source_type": "github"}, {"comment_id": 3, "body": "Here is the contents of log/debug.log\n[2016-03-12 18:33:38,171] DEBUG    PluginManager Loading plugin: AnnounceZero\n[2016-03-12 18:33:38,179] DEBUG    PluginManager New plugin registered to: Site\n[2016-03-12 18:33:38,179] DEBUG    PluginManager Loading plugin: CryptMessage\n[2016-03-12 18:33:38,245] DEBUG    - opensslVerify loaded: <CDLL '/usr/lib/libssl.dylib', handle 10185fa30 at 1039595d0>\n[2016-03-12 18:33:38,248] INFO     - OpenSSL loaded, version: 0009081DF\n[2016-03-12 18:33:38,249] DEBUG    PluginManager New plugin registered to: UiWebsocket\n[2016-03-12 18:33:38,249] DEBUG    PluginManager New plugin registered to: User\n[2016-03-12 18:33:38,249] DEBUG    PluginManager Loading plugin: Newsfeed\n[2016-03-12 18:33:38,250] DEBUG    PluginManager New plugin registered to: UiWebsocket\n[2016-03-12 18:33:38,250] DEBUG    PluginManager New plugin registered to: User\n[2016-03-12 18:33:38,251] DEBUG    PluginManager Loading plugin: Sidebar\n[2016-03-12 18:33:38,258] DEBUG    PluginManager New plugin registered to: UiRequest\n[2016-03-12 18:33:38,258] DEBUG    PluginManager New plugin registered to: UiWebsocket\n[2016-03-12 18:33:38,258] DEBUG    PluginManager Loading plugin: Stats\n[2016-03-12 18:33:38,266] DEBUG    PluginManager New plugin registered to: UiRequest\n[2016-03-12 18:33:38,266] DEBUG    PluginManager Loading plugin: Trayicon\n[2016-03-12 18:33:38,266] DEBUG    PluginManager Loading plugin: Zeroname\n[2016-03-12 18:33:38,268] DEBUG    PluginManager New plugin registered to: UiRequest\n[2016-03-12 18:33:38,269] DEBUG    PluginManager New plugin registered to: SiteManager\n[2016-03-12 18:33:38,269] DEBUG    - Config: Config(action='main', batch=False, coffeescript_compiler=None, config_file='zeronet.conf', connected_limit=15, data_dir='data', debug=False, debug_gevent=False, debug_socket=False, disable_encryption=False, disable_sslcompression=True, disable_udp=False, fileserver_ip='*', fileserver_port=15441, homepage='1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D', ip_external=None, keep_ssl_cert=False, log_dir='log', max_files_opened=2048, msgpack_purepython=True, open_browser='default_browser', proxy=None, size_limit=10, stream_downloads=False, tor='enable', tor_controller='127.0.0.1:9051', tor_proxy='127.0.0.1:9050', trackers=['zero://boot3rdez4rzn36x.onion:15441', 'zero://boot.zeronet.io#f36ca555bee6ba216b14d10f38c16f7769ff064e0e37d887603548cc2e64191d:15441', 'udp://tracker.coppersurfer.tk:6969', 'udp://tracker.leechers-paradise.org:6969', 'udp://9.rarbg.com:2710', 'http://tracker.aletorrenty.pl:2710/announce', 'http://explodie.org:6969/announce', 'http://torrent.gresille.org/announce'], trackers_file=False, ui_ip='127.0.0.1', ui_port=43110, ui_restrict=False, use_openssl=True, use_tempfiles=False, verbose=False)\n[2016-03-12 18:33:38,269] INFO     - Version: 0.3.6 r1015, Python 2.7.11 |Anaconda 2.5.0 (x86_64)| (default, Dec  6 2015, 18:57:58) \n[GCC 4.2.1 (Apple Inc. build 5577)], Gevent: 1.0.2\n[2016-03-12 18:33:38,324] DEBUG    PluginManager New class accepts plugins: SiteManager (Loaded plugins: [<class 'Zeroname.SiteManagerPlugin.SiteManagerPlugin'>, <class 'Site.SiteManager.SiteManager'>])\n[2016-03-12 18:33:38,324] DEBUG    PluginManager New class accepts plugins: Site (Loaded plugins: [<class 'AnnounceZero.AnnounceZeroPlugin.SitePlugin'>, <class 'Site.Site.Site'>])\n[2016-03-12 18:33:38,334] DEBUG    - Disabled SSL compression on <CDLL '/usr/lib/libssl.dylib', handle 10185fa30 at 103f396d0>\n[2016-03-12 18:33:38,347] DEBUG    - Missing SSLwrap, readded.\n[2016-03-12 18:33:38,347] DEBUG    - Python SSL version: OpenSSL 1.0.2f  28 Jan 2016\n[2016-03-12 18:33:38,379] DEBUG    PluginManager New class accepts plugins: User (Loaded plugins: [<class 'Newsfeed.NewsfeedPlugin.UserPlugin'>, <class 'CryptMessage.CryptMessagePlugin.UserPlugin'>, <class 'User.User.User'>])\n[2016-03-12 18:33:38,385] DEBUG    PluginManager New class accepts plugins: UiWebsocket (Loaded plugins: [<class 'Sidebar.SidebarPlugin.UiWebsocketPlugin'>, <class 'Newsfeed.NewsfeedPlugin.UiWebsocketPlugin'>, <class 'CryptMessage.CryptMessagePlugin.UiWebsocketPlugin'>, <class 'Ui.UiWebsocket.UiWebsocket'>])\n[2016-03-12 18:33:38,385] DEBUG    PluginManager New class accepts plugins: UiRequest (Loaded plugins: [<class 'Zeroname.UiRequestPlugin.UiRequestPlugin'>, <class 'Stats.StatsPlugin.UiRequestPlugin'>, <class 'Sidebar.SidebarPlugin.UiRequestPlugin'>, <class 'Ui.UiRequest.UiRequest'>])\n[2016-03-12 18:33:38,385] INFO     - Creating FileServer....\n[2016-03-12 18:33:38,386] DEBUG    TorManager Connecting to 127.0.0.1:9051\n[2016-03-12 18:33:38,388] ERROR    TorManager Tor controller connect error: error: [Errno 61] Connection refused in TorManager.py line 151 > socket.py line 344\n[2016-03-12 18:33:38,388] DEBUG    TorManager Tor proxy port 127.0.0.1:9050 check error: No connection\n[2016-03-12 18:33:38,389] INFO     - Creating UiServer....\n[2016-03-12 18:33:38,389] DEBUG    - Loading sites...\n[2016-03-12 18:33:38,389] DEBUG    - Added new site: 1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F\n[2016-03-12 18:33:38,392] ERROR    Site:1Name2..hM9F Content.json not exist: data/1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F/content.json\n[2016-03-12 18:33:38,392] DEBUG    Site:1Name2..hM9F New auth key: b8b6fbdc2b2ec0b38adbf50210917241ee2b945028af4180b2653a319b4ac4a7\n[2016-03-12 18:33:38,393] DEBUG    Site:1Name2..hM9F New wrapper key: dddf28d57c504b8b53f53dee01503ce2a860455ae013ff004dfb0fe75142e687\n[2016-03-12 18:33:38,394] INFO     - Removing old SSL certs...\n[2016-03-12 18:33:38,394] INFO     - Starting servers....\n[2016-03-12 18:33:38,394] DEBUG    Site:1Name2..hM9F Start downloading, bad_files: {}, check_size: False, blind_includes: True\n[2016-03-12 18:33:38,394] DEBUG    Site:1Name2..hM9F Downloading content.json...\n[2016-03-12 18:33:38,394] DEBUG    Site:1Name2..hM9F Need content.json first\n[2016-03-12 18:33:38,394] DEBUG    WorkerManager:1Name2..hM9F New task: content.json, peer lock: None, priority: 0, optional_hash_id: None, tasks: 1\n[2016-03-12 18:33:38,394] INFO     Ui.UiServer --------------------------------------\n[2016-03-12 18:33:38,394] INFO     Ui.UiServer Web interface: http://127.0.0.1:43110/\n[2016-03-12 18:33:38,394] INFO     Ui.UiServer --------------------------------------\n[2016-03-12 18:33:38,394] INFO     - Opening browser: default_browser...\n[2016-03-12 18:33:38,538] DEBUG    - Current RLIMIT_NOFILE: 256, changing to 2048...\n[2016-03-12 18:33:38,538] ERROR    Ui.UiServer Web interface bind error, must be running already, exiting.... [Errno 48] Address already in use: ('127.0.0.1', 43110)\n[2016-03-12 18:33:38,538] DEBUG    Ui.UiServer Stopped.\n[2016-03-12 18:33:39,114] DEBUG    - Generating RSA cert and key PEM files...Generating a 2048 bit RSA private key\n.......................................................................................................................................+++\n.......................................................................................+++\nunable to write 'random state'\n\n## writing new private key to 'data/key-rsa.pem'\n\n[2016-03-12 18:33:39,114] DEBUG    FileServer Binding to: *:15441, (msgpack: 0.4.6), supported crypt: ['tls-rsa']\n[2016-03-12 18:33:39,114] INFO     FileServer StreamServer bind error, must be running already: [Errno 48] Address already in use: ('', 15441)\n[2016-03-12 18:33:39,114] DEBUG    FileServer Stopped.\n[2016-03-12 18:33:39,115] DEBUG    Site:1Name2..hM9F Need content.json first\n\nAfter taking a look at the log, I figured that something else must be running at the port. I used lsof to show anything that was already running on the port. I think I must have been trying to run two instances of ZeroNet at the same time. Thanks for the help.\n", "added": 1457815277, "modified": 1457815277, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/336#issuecomment-195835717", "source_type": "github"}]}}