{"cert_user_id": "bugmenot2@github", "next_topic_id": 2, "topic": [{"topic_id": 1604065003, "title": "403 error", "body": " \"GATEWAY_INTERFACE\": \"CGI/1.1\", \n    \"HTTP_ACCEPT\": \"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8\", \n    \"HTTP_ACCEPT_ENCODING\": \"gzip, deflate, sdch\", \n    \"HTTP_ACCEPT_LANGUAGE\": \"en-US,en;q=0.8\", \n    \"HTTP_CACHE_CONTROL\": \"max-age=0\", \n    \"HTTP_CONNECTION\": \"keep-alive\", \n    \"HTTP_HOST\": \"127.0.0.1:43110\", \n    \"HTTP_REFERER\": \"http://127.0.0.1:43110/ZeroUpload.bit/?wrapper_nonce=bc050f29c68379a2401e2a6301a46b3a4e1b8fe9d9b32d889572ec6f76c04fc4\", \n    \"HTTP_UPGRADE_INSECURE_REQUESTS\": \"1\", \n    \"HTTP_USER_AGENT\": \"Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Dragon/45.6.11.385 Chrome/45.0.2454.93 Safari/537.36\", \n    \"PATH_INFO\": \"/ZeroUpload.bit/\", \n    \"QUERY_STRING\": \"wrapper_nonce=bc050f29c68379a2401e2a6301a46b3a4e1b8fe9d9b32d889572ec6f76c04fc4\", \n    \"REMOTE_ADDR\": \"127.0.0.1\", \n    \"REMOTE_PORT\": \"2279\", \n    \"REQUEST_METHOD\": \"GET\", \n    \"SCRIPT_NAME\": \"\", \n    \"SERVER_NAME\": \"localhost\", \n    \"SERVER_PORT\": \"43110\", \n    \"SERVER_PROTOCOL\": \"HTTP/1.1\", \n    \"SERVER_SOFTWARE\": \"gevent/1.0 Python/2.7\", \n    \"arguments\": {\n        \"action\": \"main\", \n        \"batch\": false, \n        \"coffeescript_compiler\": \"type %s | tools\\coffee\\coffee.cmd\", \n        \"config_file\": \"zeronet.conf\", \n        \"data_dir\": \"data\", \n        \"debug\": false, \n        \"debug_socket\": false, \n        \"disable_encryption\": false, \n        \"disable_sslcompression\": true, \n        \"disable_udp\": false, \n        \"fileserver_ip\": \"*\", \n        \"fileserver_port\": 15441, \n        \"homepage\": \"1EU1tbG9oC1A8jz2ouVwGZyQ5asrNsE4Vr\", \n        \"ip_external\": null, \n        \"log_dir\": \"log\", \n        \"msgpack_purepython\": true, \n        \"open_browser\": \"default_browser\", \n        \"proxy\": null, \n        \"size_limit\": 10, \n        \"stream_downloads\": false, \n        \"trackers\": [\n            \"udp://tracker.coppersurfer.tk:6969\", \n            \"udp://tracker.leechers-paradise.org:6969\", \n            \"udp://9.rarbg.com:2710\", \n            \"http://tracker.aletorrenty.pl:2710/announce\", \n            \"http://tracker.skyts.net:6969/announce\", \n            \"http://torrent.gresille.org/announce\"\n        ], \n        \"trackers_file\": false, \n        \"ui_ip\": \"127.0.0.1\", \n        \"ui_port\": 43110, \n        \"ui_restrict\": false, \n        \"use_openssl\": true, \n        \"use_tempfiles\": false\n    }, \n    \"plugins\": [\n        \"Sidebar\", \n        \"Stats\", \n        \"Trayicon\", \n        \"Zeroname\"\n    ], \n    \"version_gevent\": \"1.0.1\", \n    \"version_python\": \"2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]\", \n    \"version_zeronet\": \"0.3.3 r618\", \n    \"wsgi.url_scheme\": \"http\"\n}\n\nCould this be caused by giving your-self a name change (by editing the user.json file). I changed by name before touching ZeroUpload and it as not caused issues else where.\n", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1448154678, "modified": 1448179476, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/220", "source_type": "github"}]}