{"cert_user_id": "lezsakdomi@github", "next_comment_id": 7, "comment": {"1604066677_mirrored_trenta3_github": [{"comment_id": 1, "body": "What is when the receiver's computer is not up and running at the given timeframe?\r\n\r\nAnyways, the receiver can delete the file, sign it's `content.json` and deploy the reduced storage...\r\n\r\n@trenta3 Can you imagine any other use case?", "added": 1541776750, "modified": 1541776806, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1541#issuecomment-437448452", "source_type": "github"}], "1604066880_mirrored_DaniellMesquita_github": [{"comment_id": 2, "body": "It would be great to auto-detect whether the ZeroNet installation is in a git repo and do a pull instead of just overwriting the files. Or maybe have an option for it. Or a different branch :D\r\n\r\nPersonally I have installed ZeroNet using a simple `git clone` from GitHub, and I make some commits when I umm... personalize the source code.", "added": 1553003073, "modified": 1553003073, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1629#issuecomment-474463552", "source_type": "github"}], "1604066963_mirrored_lezsakdomi_github": [{"comment_id": 3, "body": "In the meantime, I went over the GitHub version, and I can't reproduce it any more :(", "added": 1541692725, "modified": 1541692760, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1768#issuecomment-437116020", "source_type": "github"}], "1604067169_mirrored_yurivict_github": [{"comment_id": 4, "body": "`./zeronet.py` sometimes prints a KeyboardInterrupt trace and exists, sometimes just prints `Shutting down...` and does nothing - for Ctrl+C.\r\n\r\nNo reaction for sending SIGTERM. (neither in regular or debug log)\r\n\r\n`python* -V`:\r\n| `python` | 3.6.5 |\r\n| `python2` | 2.7.15 |\r\n| `python3` | 3.6.5 |\r\n| `python3.5` | 3.5.5 |\r\n| `python3.5m` | 3.5.5 |", "added": 1553000225, "modified": 1553001182, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1905#issuecomment-474440764", "source_type": "github"}, {"comment_id": 5, "body": "`zeronet.py` from dd46a64e7911439ae4239d21e55c5fdb5cd6188f does not solve the SIGTERM issue (for me).", "added": 1553001484, "modified": 1553001484, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1905#issuecomment-474452569", "source_type": "github"}, {"comment_id": 6, "body": "Sending SIGTERM _does_ something.\r\n\r\nI sent sigterm on 2019-03-19 20:44:24. Here is the long (29M) debug log: https://files.fm/u/wjpfqdks\r\n\r\n*TL;DR it looks like ZeroNet closes connections in reaction to a SIGTERM*", "added": 1553014367, "modified": 1553014423, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1905#issuecomment-474552318", "source_type": "github"}]}, "next_topic_id": 3, "topic": [{"topic_id": 1604066963, "title": "Restart fails", "body": "### Step 1: Please describe your environment\r\n\r\n  * ZeroNet version: 0.6.4\r\n  * Operating system: Gentoo (`Linux ledomi-pc 4.12.5-gentoo #3 SMP Sat Jun 2 11:29:07 CEST 2018 x86_64 Intel(R) Core(TM)2 Duo CPU E7500 @ 2.93GHz GenuineIntel GNU/Linux`)\r\n  * Web browser: Firefox 58.0.1\r\n  * Tor status: not available\r\n  * Opened port: no\r\n  * Special configuration: Installed from the respository\r\n\r\n### Step 2: Describe the problem:\r\n\r\nWhen I try to update ZeroNet, becomes unavailable\r\n\r\n#### Steps to reproduce:\r\n\r\n  1. In ZeroHello click on three-dot menu\r\n  2. Click on _Version 0.6.4 (rev3670): Up to date!_\r\n  3. Click the yellow _Update ZeroNet_ button on top-right\r\n\r\n*__Or__*\r\n\r\n  1. Change a config\r\n  2. Click on the restart button which appears\r\n\r\n#### Observed Results:\r\n\r\nZeronet gone down for restart, but didn't start after.\r\n\r\nHere's a log from systemd:\r\n\r\n```\r\nsystemd[2]: Started ZeroNet: Decentralized websites using Bitcoin crypto and BitTorrent network.\r\nzeronet[10319]: [19:19:50] - OpenSSL loaded, version: 0100020FF\r\nzeronet[10319]: [19:19:50] - Version: 0.6.4 r3670, Python 2.7.14 (default, Mar 31 2018, 04:20:41)\r\nzeronet[10319]: [GCC 6.4.0], Gevent: 1.2.1\r\nzeronet[10319]: [19:19:50] - Creating FileServer....\r\nzeronet[10319]: [19:19:50] - Creating UiServer....\r\nzeronet[10319]: [19:19:50] - Removing old SSL certs...\r\nzeronet[10319]: [19:19:50] - Starting servers....\r\nzeronet[10319]: [19:19:50] Ui.UiServer --------------------------------------\r\nzeronet[10319]: [19:19:50] Ui.UiServer Web interface: http://127.0.0.1:43110/\r\nzeronet[10319]: [19:19:50] Ui.UiServer --------------------------------------\r\nzeronet[10319]: [19:19:50] TorManager Connecting to Tor Controller 127.0.0.1:9051\r\nzeronet[10319]: [19:19:50] TorManager Tor controller connect error: error: [Errno 111] Connection refused in TorManager.py line 190 > _socket2.py line 231\r\nzeronet[10319]: [19:19:50] TorManager Disabling Tor, because error while accessing Tor proxy at port 127.0.0.1:9050: No connection\r\nzeronet[10319]: [19:19:50] Site:1Name2..hM9F Tracker udp://5.79.83.193:6969 announce failed: [Errno 111] Connection refused in mode startup\r\nzeronet[10319]: [19:19:51] ConnServer Checking port 23239 using portchecker.co...\r\nzeronet[10319]: [19:19:52] ConnServer [BAD :(] Port closed: Port 23239 is closed.\r\nzeronet[10319]: [19:19:52] ConnServer Trying to open port using UpnpPunch...\r\nzeronet[10319]: [19:19:59] Site:1HeLLo..Tf3D Tracker udp://5.79.83.193:6969 announce failed: Could not connect in mode startup\r\nzeronet[10319]: [19:20:02] ConnServer UpnpPunch run error: UpnpError: Failed to communicate with igd using port 23239 on local machine after 3 tries. in FileServer.py line 118 > UpnpPunch.py line 349 > UpnpPunch>\r\nzeronet[10319]: [19:20:03] - All server stopped\r\nzeronet[10319]: [19:20:03] - Unhandled exception: No module named update\r\nzeronet[10319]: Traceback (most recent call last):\r\nzeronet[10319]:   File \"/usr/share/zeronet/zeronet.py\", line 22, in main\r\nzeronet[10319]:     import update\r\nzeronet[10319]:   File \"/usr/lib64/python2.7/site-packages/gevent/builtins.py\", line 93, in __import__\r\nzeronet[10319]:     result = _import(*args, **kwargs)\r\nzeronet[10319]: ImportError: No module named update\r\nzeronet[10319]: No handlers could be found for logger \"SiteManager\"\r\nzeronet[10319]: DEBUG:-:Trying using local ip: 192.168.1.54\r\nzeronet[10319]: DEBUG:Ui.UiServer:127.0.0.1 - - [2018-11-06 19:20:04] \"GET /Websocket?wrapper_key=c470351a0993ef674929395eed87f5a763b8bae2645743ca73f887764794208d HTTP/1.1\" 101 129 12.305931\r\nzeronet[10319]: - Starting ZeroNet...\r\nzeronet[10319]: Can't open lock file, your ZeroNet client is probably already running, exiting... ([Errno 11] Resource temporarily unavailable)\r\n```\r\n\r\nAnd service goes failed status.\r\n\r\n*__Or__*\r\n\r\nWhen installed manually and started using `./ZeroNet.sh`:\r\n\r\n```\r\n...\r\n[20:22:06] - All server stopped\r\nRestarting...\r\nNo handlers could be found for logger \"SiteManager\"\r\nDEBUG:-:Gevent block detected: 0.124728918076\r\nDEBUG:Ui.UiServer:127.0.0.1 - - [2018-11-06 20:22:07] \"GET /Websocket?wrapper_key=b25fc570c362b991eb24aef00a1323733e2a94cf542550c5c430956b24db755b HTTP/1.1\" 101 129 8.978960\r\nExecuting /home/led/Downloads/ZeroBundle/ZeroNet/../Python/python2.7 ['/home/led/Downloads/ZeroBundle/ZeroNet/../Python/python2.7', 'start.py', '--open_browser', 'default_browser']\r\n- Starting ZeroNet...\r\nCan't open lock file, your ZeroNet client is probably already running, exiting... ([Errno 11] Resource temporarily unavailable)\r\nOpening browser: %s... default_browser\r\nThis tool has been deprecated, use 'gio open' instead.\r\nSee 'gio help open' for more info.\r\n\r\n```\r\n\r\n#### Expected Results:\r\n\r\nZeroNet simply restarts.", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1541518421, "modified": 1541692760, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1768", "source_type": "github"}, {"topic_id": 1604066965, "title": "Server error when enabling Multiuser plugin", "body": "### Step 1: Please describe your environment\r\n\r\n  * ZeroNet version: 0.6.4\r\n  * Operating system: Gentoo (`Linux ledomi-pc 4.12.5-gentoo #3 SMP Sat Jun 2 11:29:07 CEST 2018 x86_64 Intel(R) Core(TM)2 Duo CPU E7500 @ 2.93GHz GenuineIntel GNU/Linux`)\r\n  * Web browser: Firefox 58.0.1\r\n  * Tor status: not available\r\n  * Opened port: no\r\n  * Special configuration: Installed from the respository\r\n\r\n### Step 2: Describe the problem:\r\n\r\nCan't load ZeroHello when Multiuser plugin enabled\r\n\r\n#### Steps to reproduce:\r\n\r\n  0. `systemctl stop zeronet`\r\n  1. `mv /usr/share/zeronet/plugins/{disabled-,}Multiuser`\r\n  2. (optional) `rm -r /var/lib/zeronet/*`\r\n  3. `systemctl start zeronet`\r\n  4. `gio open http://127.0.0.1:43110`\r\n\r\n#### Observed Results:\r\n\r\nOf course zeronet redirects to `http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D`, but I am presented with this ServerError:\r\n\r\n```\r\nServer error\r\nErr: AttributeError: 'NoneType' object has no attribute 'settings' in UiServer.py line 104 > UiRequest.py line 144 > UiConfigPlugin.py line 21 > MultiuserPlugin.py line 56 > ContentFilterPlugin.py line 184 > UiRequest.py line 344 > UiRequest.py line 421\r\nPlease report it if you think this an error.\r\nDetails:\r\n\r\n{\r\n    \"GATEWAY_INTERFACE\": \"CGI/1.1\", \r\n    \"HTTP_ACCEPT\": \"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\", \r\n    \"HTTP_ACCEPT_ENCODING\": \"gzip, deflate\", \r\n    \"HTTP_ACCEPT_LANGUAGE\": \"hu-HU,hu;q=0.8,en-US;q=0.5,en;q=0.3\", \r\n    \"HTTP_CACHE_CONTROL\": \"max-age=0\", \r\n    \"HTTP_CONNECTION\": \"keep-alive\", \r\n    \"HTTP_HOST\": \"127.0.0.1:43110\", \r\n    \"HTTP_UPGRADE_INSECURE_REQUESTS\": \"1\", \r\n    \"HTTP_USER_AGENT\": \"Mozilla/5.0 (X11; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0\", \r\n    \"PATH_INFO\": \"/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/\", \r\n    \"QUERY_STRING\": \"\", \r\n    \"REMOTE_ADDR\": \"127.0.0.1\", \r\n    \"REMOTE_PORT\": \"34246\", \r\n    \"REQUEST_METHOD\": \"GET\", \r\n    \"SCRIPT_NAME\": \"\", \r\n    \"SERVER_NAME\": \"localhost\", \r\n    \"SERVER_PORT\": \"43110\", \r\n    \"SERVER_PROTOCOL\": \"HTTP/1.1\", \r\n    \"SERVER_SOFTWARE\": \"gevent/1.2 Python/2.7\", \r\n    \"arguments\": {\r\n        \"action\": \"main\", \r\n        \"autodownload_bigfile_size_limit\": 1, \r\n        \"batch\": false, \r\n        \"bind\": null, \r\n        \"bit_resolver\": \"1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F\", \r\n        \"broadcast_port\": 1544, \r\n        \"coffeescript_compiler\": null, \r\n        \"config_file\": \"/etc/zeronet.conf\", \r\n        \"connected_limit\": 8, \r\n        \"data_dir\": \"/var/lib/zeronet\", \r\n        \"db_mode\": \"speed\", \r\n        \"debug\": false, \r\n        \"debug_socket\": false, \r\n        \"disable_db\": false, \r\n        \"disable_encryption\": false, \r\n        \"disable_sslcompression\": true, \r\n        \"disable_udp\": false, \r\n        \"download_optional\": \"manual\", \r\n        \"end\": false, \r\n        \"file_size_limit\": 10, \r\n        \"fileserver_ip\": \"*\", \r\n        \"fileserver_port\": 23239, \r\n        \"fileserver_port_range\": \"10000-40000\", \r\n        \"fix_float_decimals\": false, \r\n        \"force_encryption\": false, \r\n        \"global_connected_limit\": 512, \r\n        \"homepage\": \"1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D\", \r\n        \"ip_external\": null, \r\n        \"ip_local\": [\r\n            \"127.0.0.1\"\r\n        ], \r\n        \"keep_ssl_cert\": false, \r\n        \"language\": \"hu\", \r\n        \"log_dir\": \"/var/log/zeronet\", \r\n        \"log_level\": \"DEBUG\", \r\n        \"max_files_opened\": 2048, \r\n        \"msgpack_purepython\": false, \r\n        \"multiuser_local\": false, \r\n        \"multiuser_no_new_sites\": false, \r\n        \"open_browser\": null, \r\n        \"optional_limit\": \"10%\", \r\n        \"optional_limit_exclude_minsize\": 20, \r\n        \"proxy\": null, \r\n        \"silent\": false, \r\n        \"size_limit\": 10, \r\n        \"stack_size\": null, \r\n        \"stream_downloads\": false, \r\n        \"tor\": \"enable\", \r\n        \"tor_controller\": \"127.0.0.1:9051\", \r\n        \"tor_hs_limit\": 10, \r\n        \"tor_hs_port\": 15441, \r\n        \"tor_proxy\": \"127.0.0.1:9050\", \r\n        \"tor_use_bridges\": false, \r\n        \"trackers\": [\r\n            \"zero://boot3rdez4rzn36x.onion:15441\", \r\n            \"zero://zero.booth.moe#f36ca555bee6ba216b14d10f38c16f7769ff064e0e37d887603548cc2e64191d:443\", \r\n            \"udp://tracker.coppersurfer.tk:6969\", \r\n            \"udp://5.79.83.193:6969\", \r\n            \"udp://104.238.198.186:8000\", \r\n            \"http://tracker.swateam.org.uk:2710/announce\", \r\n            \"http://open.acgnxtracker.com:80/announce\", \r\n            \"http://retracker.mgts.by:80/announce\"\r\n        ], \r\n        \"trackers_file\": false, \r\n        \"trackers_proxy\": \"disable\", \r\n        \"ui_host\": null, \r\n        \"ui_ip\": \"127.0.0.1\", \r\n        \"ui_port\": 43110, \r\n        \"ui_restrict\": false, \r\n        \"ui_trans_proxy\": false, \r\n        \"updatesite\": \"1UPDatEDxnvHDo7TXvq6AEBARfNkyfxsp\", \r\n        \"use_openssl\": true, \r\n        \"use_tempfiles\": false, \r\n        \"verbose\": false, \r\n        \"workers\": 5, \r\n        \"working_shared_trackers_limit\": 5\r\n    }, \r\n    \"plugins\": [\r\n        \"AnnounceLocal\", \r\n        \"AnnounceShare\", \r\n        \"AnnounceZero\", \r\n        \"Bigfile\", \r\n        \"Chart\", \r\n        \"ContentFilter\", \r\n        \"Cors\", \r\n        \"CryptMessage\", \r\n        \"FilePack\", \r\n        \"MergerSite\", \r\n        \"Multiuser\", \r\n        \"Newsfeed\", \r\n        \"OptionalManager\", \r\n        \"PeerDb\", \r\n        \"Sidebar\", \r\n        \"Stats\", \r\n        \"TranslateSite\", \r\n        \"Trayicon\", \r\n        \"UiConfig\", \r\n        \"Zeroname\"\r\n    ], \r\n    \"version_gevent\": \"1.2.1\", \r\n    \"version_python\": \"2.7.14 (default, Mar 31 2018, 04:20:41) \\n[GCC 6.4.0]\", \r\n    \"version_zeronet\": \"0.6.4 r3670\", \r\n    \"wsgi.url_scheme\": \"http\"\r\n}\r\n```\r\n\r\n#### Expected Results:\r\n\r\nZeroHello loads as usual, but I can use the program multiuserly somehow. But anyways, nothing other than a crash.", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1541518784, "modified": 1541521378, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1769", "source_type": "github"}]}