{"cert_user_id": "drjmedulla@github", "next_comment_id": 4, "comment": {"1604065246_mirrored_HelloZeroNet_github": [{"comment_id": 1, "body": "Downloaded Zeronet per https://zeronet.io/ started up and worked great.\nTried to re-start the Zeronet Desktop App after my laptop went to sleep.\n[Mac OS 10.11.3]\nThis is what I get:\n\n**Server error\n\nErr: Exception: File not allowed: data/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/index.html in UiServer.py line 81 > UiRequest.py line 82 > UiRequest.py line 209 > UiRequest.py line 282 > SiteStorage.py line 230 > SiteStorage.py line 251\n\nPlease report it if you think this an error.\n\nDetails:**\n\n{\n    \"GATEWAY_INTERFACE\": \"CGI/1.1\", \n    \"HTTP_ACCEPT\": \"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8\", \n    \"HTTP_ACCEPT_ENCODING\": \"gzip, deflate, sdch\", \n    \"HTTP_ACCEPT_LANGUAGE\": \"en-US,en;q=0.8\", \n    \"HTTP_CONNECTION\": \"keep-alive\", \n    \"HTTP_HOST\": \"127.0.0.1:43110\", \n    \"HTTP_UPGRADE_INSECURE_REQUESTS\": \"1\", \n    \"HTTP_USER_AGENT\": \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36\", \n    \"PATH_INFO\": \"/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D\", \n    \"QUERY_STRING\": \"\", \n    \"REMOTE_ADDR\": \"127.0.0.1\", \n    \"REMOTE_PORT\": \"61010\", \n    \"REQUEST_METHOD\": \"GET\", \n    \"SCRIPT_NAME\": \"\", \n    \"SERVER_NAME\": \"1.0.0.127.in-addr.arpa\", \n    \"SERVER_PORT\": \"43110\", \n    \"SERVER_PROTOCOL\": \"HTTP/1.1\", \n    \"SERVER_SOFTWARE\": \"gevent/1.0 Python/2.7\", \n    \"arguments\": {\n        \"action\": \"main\", \n        \"batch\": false, \n        \"coffeescript_compiler\": null, \n        \"config_file\": \"zeronet.conf\", \n        \"connected_limit\": 15, \n        \"data_dir\": \"data\", \n        \"debug\": false, \n        \"debug_gevent\": false, \n        \"debug_socket\": false, \n        \"disable_encryption\": false, \n        \"disable_sslcompression\": true, \n        \"disable_udp\": false, \n        \"fileserver_ip\": \"*\", \n        \"fileserver_port\": 15441, \n        \"homepage\": \"1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D\", \n        \"ip_external\": null, \n        \"keep_ssl_cert\": false, \n        \"log_dir\": \"log\", \n        \"max_files_opened\": 2048, \n        \"msgpack_purepython\": true, \n        \"open_browser\": \"default_browser\", \n        \"proxy\": null, \n        \"size_limit\": 10, \n        \"stream_downloads\": false, \n        \"tor\": \"enable\", \n        \"tor_controller\": \"127.0.0.1:9051\", \n        \"tor_proxy\": \"127.0.0.1:9050\", \n        \"trackers\": [\n            \"zero://boot3rdez4rzn36x.onion:15441\", \n            \"zero://boot.zeronet.io#f36ca555bee6ba216b14d10f38c16f7769ff064e0e37d887603548cc2e64191d:15441\", \n            \"udp://tracker.coppersurfer.tk:6969\", \n            \"udp://tracker.leechers-paradise.org:6969\", \n            \"udp://9.rarbg.com:2710\", \n            \"http://tracker.aletorrenty.pl:2710/announce\", \n            \"http://explodie.org:6969/announce\", \n            \"http://torrent.gresille.org/announce\"\n        ], \n        \"trackers_file\": false, \n        \"ui_ip\": \"127.0.0.1\", \n        \"ui_port\": 43110, \n        \"ui_restrict\": false, \n        \"use_openssl\": true, \n        \"use_tempfiles\": false, \n        \"verbose\": false\n    }, \n    \"plugins\": [\n        \"AnnounceZero\", \n        \"CryptMessage\", \n        \"Newsfeed\", \n        \"Sidebar\", \n        \"Stats\", \n        \"Trayicon\", \n        \"Zeroname\"\n    ], \n    \"version_gevent\": \"1.0.2\", \n    \"version_python\": \"2.7.11 |Anaconda 2.5.0 (x86_64)| (default, Dec  6 2015, 18:57:58) \\n[GCC 4.2.1 (Apple Inc. build 5577)]\", \n    \"version_zeronet\": \"0.3.6 r1038\", \n    \"wsgi.url_scheme\": \"http\"\n}\n", "added": 1458338710, "modified": 1458338781, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/363#issuecomment-198596991", "source_type": "github"}, {"comment_id": 2, "body": "1st Question: No, I do not have any special (non-english) characters in the directory.\n\nI searched `not in allowed dir` and did not find any associated code.\n\nHere is the closest I found: `[2016-03-18 20:59:33,542] ERROR    Site:1Name2..hM9F Content.json not exist: data/1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F/content.json`\n", "added": 1458343576, "modified": 1458343590, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/363#issuecomment-198617015", "source_type": "github"}, {"comment_id": 3, "body": "Python 2.7 is only running once.\nI attached a screenshot of Python running as well as the log files Zipped.\n\n![screen shot 2016-03-19 at 8 30 07 am](https://cloud.githubusercontent.com/assets/16785963/13898606/f3882172-edac-11e5-933e-59ee0a531dd1.png)\n\n[Archive.zip](https://github.com/HelloZeroNet/ZeroNet/files/180806/Archive.zip)\n", "added": 1458380015, "modified": 1458380015, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/363#issuecomment-198694936", "source_type": "github"}]}}