{"cert_user_id": "bitcoren@github", "next_topic_id": 6, "topic": [{"topic_id": 1604066504, "title": "sitePublish is not working", "body": "### Step 1: Please describe your environment\r\n\r\n  * ZeroNet version: 3417\r\n  * Operating system: Ubuntu 16.04\r\n  * Web browser: -\r\n  * Tor status: always\r\n  * Opened port: yes\r\n  * Special configuration: -\r\n\r\nsitePublish is not working after changing zite\r\n\r\nbitcoren@nCoin:~$ ~/ZeroNet-0.6.2/zeronet.py sitePublish 1FbmSKV653gt8Q7Cf6ozAf2CUCTmwmtSkE\r\n- Starting ZeroNet...\r\n- OpenSSL loaded, version: 01000207F\r\n- Version: 0.6.2 r3417, Python 2.7.12 (default, Dec  4 2017, 14:50:18) \r\n[GCC 5.4.0 20160609], Gevent: 1.2.2\r\n- Loading site...\r\n- Unhandled exception: 'NoneType' object has no attribute 'settings'\r\nTraceback (most recent call last):\r\n  File \"/home/bitcoren/ZeroNet-0.6.2/zeronet.py\", line 19, in main\r\n    main.start()\r\n  File \"/home/bitcoren/ZeroNet-0.6.2/src/main.py\", line 537, in start\r\n    actions.call(config.action, action_kwargs)\r\n  File \"/home/bitcoren/ZeroNet-0.6.2/src/main.py\", line 157, in call\r\n    back = func(**kwargs)\r\n  File \"/home/bitcoren/ZeroNet-0.6.2/src/main.py\", line 395, in sitePublish\r\n    site.settings[\"serving\"] = True  # Serving the site even if its disabled\r\nAttributeError: 'NoneType' object has no attribute 'settings'\r\n- Unhandled exception\r\nNone\r\nTraceback (most recent call last):\r\n  File \"/home/bitcoren/ZeroNet-0.6.2/zeronet.py\", line 91, in <module>\r\n    main()\r\n  File \"/home/bitcoren/ZeroNet-0.6.2/zeronet.py\", line 64, in main\r\n    traceback.print_exc(file=open(config.log_dir + \"/error.log\", \"a\"))\r\nAttributeError: 'Config' object has no attribute 'log_dir'\r\n", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1524639405, "modified": 1524648869, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1404", "source_type": "github"}, {"topic_id": 1604066627, "title": "Some optional files can not be downloaded", "body": "### Step 1: Please describe your environment\r\n\r\n  * ZeroNet version: 3565\r\n  * Operating system: windows 10 / Linux\r\n  * Web browser: Firefox / IE\r\n  * Tor status: enabled/disabled\r\n  * Opened port: yes\r\n\r\nSome optional files can not be downloaded\r\nFor example:\r\nhttp://127.0.0.1:43110/1uPLoaDwKzP6MCGoVzw48r4pxawRBdmQc/data/users/1NVmmyd8EodLq35QeTbrCm5yAzrtukxRdR/1523041289-1509681876-fqrjjh.zip\r\n\r\nOn 150 peers not downloads\r\n\r\nAnd over random .JSON, .ZIP optional files\r\nhttp://localhost:43110/18VUW8Q41aexfwgFTFRJrxqtCqjvdLhLxY/storage/name_filter_all.json\r\n\r\nAfter sign and publish from web interface 18VUW8Q41aexfwgFTFRJrxqtCqjvdLhLxY works well.", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1533417845, "modified": 1535263859, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1502", "source_type": "github"}, {"topic_id": 1604066678, "title": "Sing from command line does not work on big opional files", "body": "  * ZeroNet version: 3571\r\n  * Operating system: windows 10 / Linux\r\n  * Web browser: Firefox / Vivaldi\r\n  * Tor status: enabled/disabled\r\n  * Opened port: yes\r\n\r\nI can not download big optional file: http://localhost:43110/18VUW8Q41aexfwgFTFRJrxqtCqjvdLhLxY/storage/name_filter_all.zip\r\nif i sign and publish it from command line.\r\nThen if sign from web interface download is good.", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1535508797, "modified": 1535508797, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1543", "source_type": "github"}, {"topic_id": 1604067230, "title": "siteCmd command did not work", "body": "### Step 1: Please describe your environment\r\n\r\n  * ZeroNet version: 4053\r\n  * Operating system: Ubuntu 18.04\r\n  * Web browser: Vivaldi\r\n  * Tor status: not available\r\n  * Opened port: yes\r\n\r\n### Step 2: Describe the problem:\r\n```\r\nbitcoren@name:~/ZeroNet-py3$ python3 zeronet.py siteCmd 1KoLHoz1nSddbuf6HbfP19F7Ht7xNBSa6m fileGet content.json\r\n- Starting ZeroNet...\r\n- Libsecpk256k1 loaded\r\n- Version: 0.7.0 r4053, Python 3.6.7 (default, Oct 22 2018, 11:32:17) \r\n[GCC 8.2.0], Gevent: 1.4.0\r\nFileServer IPv6 not supported: [Errno 101] Network is unreachable\r\n- Unhandled exception: Expecting value: line 1 column 1 (char 0)\r\nTraceback (most recent call last):\r\n  File \"zeronet.py\", line 23, in main\r\n    main.start()\r\n  File \"/home/bitcoren/ZeroNet-py3/src/main.py\", line 515, in start\r\n    actions.call(config.action, action_kwargs)\r\n  File \"/home/bitcoren/ZeroNet-py3/src/main.py\", line 111, in call\r\n    back = func(**kwargs)\r\n  File \"/home/bitcoren/ZeroNet-py3/src/main.py\", line 333, in siteCmd\r\n    res = json.loads(ws.recv())\r\n  File \"/usr/lib/python3.6/json/__init__.py\", line 354, in loads\r\n    return _default_decoder.decode(s)\r\n  File \"/usr/lib/python3.6/json/decoder.py\", line 339, in decode\r\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\r\n  File \"/usr/lib/python3.6/json/decoder.py\", line 357, in raw_decode\r\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\r\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\r\n```", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1554929666, "modified": 1556126057, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1979", "source_type": "github"}, {"topic_id": 1604067312, "title": "Error on update windows version", "body": "### Step 1: Please describe your environment\r\n\r\n  * ZeroNet version: rev4102\r\n  * Operating system: WIndows LTSC 2019\r\n  * Web browser: Vivaldi\r\n  * Tor status: available\r\n  * Opened port: yes\r\n\r\n### Step 2: Describe the problem:\r\nError on update windows version\r\n![1](https://user-images.githubusercontent.com/38252897/59142564-e6df5e00-89f2-11e9-8d9f-a27a5613d63d.png)\r\n\r\n#### Steps to reproduce:\r\nClick \"Update to latest version\" -> \"Update\"\r\n\r\n#### Observed Results:\r\n\r\n```\r\n[2019-06-08 13:42:06,419] DEBUG    Site:1CpGZy..bEzd Pex result: from 2 peers got 0 new peers.\r\n[2019-06-08 13:42:06,426] DEBUG    WorkerManager:1BLueG..tG49 45.76.79.97:20018: No task found, stopping (downloaded files: 0, failed: 1)\r\n[2019-06-08 13:42:06,426] DEBUG    WorkerManager:1BLueG..tG49 Removed worker, workers: 1/5\r\n[2019-06-08 13:42:06,739] DEBUG    WorkerManager:1BLueG..tG49 69.128.228.105:26187: No task found, stopping (downloaded files: 0, failed: 1)\r\n[2019-06-08 13:42:06,739] DEBUG    WorkerManager:1BLueG..tG49 Removed worker, workers: 0/5\r\n[2019-06-08 13:42:06,740] DEBUG    WorkerManager:1BLueG..tG49 Starting new workers... (tasks: 1)\r\n[2019-06-08 13:42:06,740] DEBUG    WorkerManager:1BLueG..tG49 Starting workers (Removed worker), tasks: 1, peers: 0, workers: 0\r\n[2019-06-08 13:42:06,740] DEBUG    WorkerManager:1BLueG..tG49 Added worker: 5.9.9.18:33817, workers: 1/5\r\n[2019-06-08 13:42:06,741] DEBUG    WorkerManager:1BLueG..tG49 Added worker: 167.179.116.140:34259, workers: 2/5\r\n[2019-06-08 13:42:06,776] DEBUG    SiteManager Saved sites in 0.01s (generate: 0.00s, write: 0.01s)\r\n[2019-06-08 13:42:06,777] DEBUG    SiteManager Updated merger sites in 0.000s\r\n[2019-06-08 13:42:06,777] DEBUG    BroadcastServer Stopping, socket: <gevent._socket3.socket object, fd=548, family=2, type=2, proto=0>\r\n[2019-06-08 13:42:06,778] DEBUG    ConnServer Closing port 35381\r\n[2019-06-08 13:42:06,778] DEBUG    Upnp Trying to close port 35381.\r\n[2019-06-08 13:42:06,779] DEBUG    BroadcastServer Stopped listening on port 1544\r\n[2019-06-08 13:42:06,780] DEBUG    Upnp Trying using local ip: 192.168.1.4\r\n[2019-06-08 13:42:06,838] DEBUG    Upnp Sending UPnP request to 192.168.1.1:59152...\r\n[2019-06-08 13:42:06,840] DEBUG    WorkerManager:1BLueG..tG49 5.9.9.18:33817: Verify failed: data/users/1yvSQH5Z7aJra4y9s6KG2kjLeGXYhNgn7/data.json, error: Download failed, failed peers: 6, workers: 0\r\n[2019-06-08 13:42:06,862] DEBUG    Upnp 200\r\n[2019-06-08 13:42:06,881] INFO     ConnServer Closed port via upnp.\r\n[2019-06-08 13:42:06,881] DEBUG    ConnServer Stopping\r\n[2019-06-08 13:42:07,005] DEBUG    Site:1F4WVH..jVHC Pex result: from 2 peers got 1 new peers.\r\n[2019-06-08 13:42:07,195] DEBUG    WorkerManager:1BLueG..tG49 167.179.116.140:34259: Verify failed: data/users/1yvSQH5Z7aJra4y9s6KG2kjLeGXYhNgn7/data.json, error: Download failed, failed peers: 7, workers: 0\r\n[2019-06-08 13:42:07,476] DEBUG    Site:1Gif7P..Xc7h Retry 1 bad files\r\n[2019-06-08 13:42:07,476] DEBUG    Site:1Gif7P..Xc7h Need connections: 6, Current: 17, Total: 267\r\n[2019-06-08 13:42:07,883] DEBUG    Ui.UiServer Stopping...\r\n[2019-06-08 13:42:07,883] DEBUG    Ui.UiServer Socket closed: 2\r\n[2019-06-08 13:42:07,884] DEBUG    ConnServer Stopped.\r\n[2019-06-08 13:42:07,927] DEBUG    Site:1Gif7P..Xc7h Pex result: from 2 peers got 0 new peers.\r\n[2019-06-08 13:42:07,942] DEBUG    WorkerManager:1BLueG..tG49 5.9.9.18:33817: No task found, stopping (downloaded files: 0, failed: 1)\r\n[2019-06-08 13:42:07,942] DEBUG    WorkerManager:1BLueG..tG49 Removed worker, workers: 1/5\r\n[2019-06-08 13:42:07,985] DEBUG    Ui.UiServer Stopped.\r\n[2019-06-08 13:42:07,986] INFO     - All server stopped\r\n[2019-06-08 13:42:07,989] ERROR    - Unhandled exception: [(<class 'TypeError'>, TypeError(\"update() got an unexpected keyword argument 'restart_win'\"), <traceback object at 0x00000293F67F06C8>)]\r\n[2019-06-08 13:42:12,314] DEBUG    TorManager Stopping...\r\n[2019-06-08 13:42:12,314] DEBUG    TorManager > SIGNAL SHUTDOWN\r\n[2019-06-08 13:42:12,316] DEBUG    Site:1GrEen..yt7i Need connections: 6, Current: 8, Total: 110\r\n[2019-06-08 13:42:12,316] DEBUG    - Gevent block detected: 3.4486684799194336\r\n[2019-06-08 13:42:12,316] DEBUG    Ui.UiServer 127.0.0.1 - - [2019-06-08 13:42:12] \"GET /ZeroNet-Internal/Websocket?wrapper_key=d8d95dce841b6df8a4a81816bb483689410576ba660e9e2855dd76c49162b25a HTTP/1.1\" 101 129 309.441518\r\n[2019-06-08 13:42:12,317] DEBUG    WorkerManager:1BLueG..tG49 Tasks: 1, started: 1, bad files: 3, total started: 1\r\n[2019-06-08 13:42:12,321] DEBUG    TorManager < 250 OK\r\n[2019-06-08 13:42:12,321] DEBUG    Site:1MaiL5..Ju27 Queried hashfield from 2 peers in 6.349s\r\n[2019-06-08 13:42:12,344] DEBUG    ConnServer Conn#41 msx54wus5q5afpyg.onion [v2] > Closing connection: MessageLoop ended (closed: False), waiting_requests: 0, sites: 12, buff: 0...\r\n[2019-06-08 13:42:12,345] DEBUG    ConnServer Conn#80 socec5jlid3szz6y.onion [v2] > Closing connection: MessageLoop ended (closed: False), waiting_requests: 0, sites: 2, buff: 0...\r\n[2019-06-08 13:42:12,417] DEBUG    WorkerManager:1BLueG..tG49 167.179.116.140:34259: No task found, stopping (downloaded files: 0, failed: 1)\r\n[2019-06-08 13:42:12,417] DEBUG    WorkerManager:1BLueG..tG49 Removed worker, workers: 0/5\r\n[2019-06-08 13:42:12,417] DEBUG    WorkerManager:1BLueG..tG49 Starting new workers... (tasks: 1)\r\n[2019-06-08 13:42:12,417] DEBUG    WorkerManager:1BLueG..tG49 Starting workers (Removed worker), tasks: 1, peers: 0, workers: 0\r\n[2019-06-08 13:42:12,500] DEBUG    ConnServer Checkconnections ended\r\n[2019-06-08 13:42:12,570] DEBUG    SiteManager Saved sites in 0.01s (generate: 0.04s, write: 0.01s)\r\n[2019-06-08 13:42:12,570] DEBUG    SiteManager Updated merger sites in 0.000s\r\n[2019-06-08 13:42:12,572] DEBUG    Site:12h51u..WWtv Peers saved in 0.002s\r\n[2019-06-08 13:42:12,575] DEBUG    Site:138R53..NXLP Peers saved in 0.002s\r\n[2019-06-08 13:42:12,577] DEBUG    Site:1Apr5b..6QgE Peers saved in 0.002s\r\n[2019-06-08 13:42:12,578] DEBUG    Site:1BLoGB..wfTV Peers saved in 0.001s\r\n[2019-06-08 13:42:12,581] DEBUG    Site:1BLogC..AGg8 Peers saved in 0.003s\r\n[2019-06-08 13:42:12,583] DEBUG    Site:1BLueG..tG49 Peers saved in 0.001s\r\n[2019-06-08 13:42:12,583] DEBUG    Site:1CpGZy..bEzd Peers saved in 0.000s\r\n[2019-06-08 13:42:12,584] DEBUG    Site:1F4WVH..jVHC Peers saved in 0.000s\r\n[2019-06-08 13:42:12,588] DEBUG    Site:1Gif7P..Xc7h Peers saved in 0.004s\r\n[2019-06-08 13:42:12,589] DEBUG    Site:1GrEen..yt7i Peers saved in 0.001s\r\n[2019-06-08 13:42:12,596] DEBUG    Site:1HeLLo..Tf3D Peers saved in 0.007s\r\n[2019-06-08 13:42:12,597] DEBUG    Site:1KNmG5..rZqi Peers saved in 0.001s\r\n[2019-06-08 13:42:12,598] DEBUG    Site:1KoLHo..Sa6m Peers saved in 0.000s\r\n[2019-06-08 13:42:12,601] DEBUG    Site:1MaiL5..Ju27 Peers saved in 0.003s\r\n[2019-06-08 13:42:12,604] DEBUG    Site:1MeFqF..q7nH Peers saved in 0.003s\r\n[2019-06-08 13:42:12,605] DEBUG    Site:1N9sU8..vwMd Peers saved in 0.001s\r\n[2019-06-08 13:42:12,612] DEBUG    Site:1Name2..hM9F Peers saved in 0.007s\r\n[2019-06-08 13:42:12,613] DEBUG    Site:1RedkC..uFdL Peers saved in 0.001s\r\n[2019-06-08 13:42:12,618] DEBUG    Site:1SiTEs..tdwB Peers saved in 0.004s\r\n[2019-06-08 13:42:12,620] DEBUG    Site:1SunAW..JN9a Peers saved in 0.002s\r\n[2019-06-08 13:42:12,623] DEBUG    Site:1TaLkF..jipT Peers saved in 0.003s\r\n[2019-06-08 13:42:12,627] DEBUG    Site:1UDbAD..MkoV Peers saved in 0.003s\r\n[2019-06-08 13:42:12,628] DEBUG    Site:1oranG..4k9v Peers saved in 0.001s\r\n[2019-06-08 13:42:12,629] DEBUG    Site:1uPDaT..NACf Peers saved in 0.001s\r\n[2019-06-08 13:42:12,632] DEBUG    Site:1uPLoa..dmQc Peers saved in 0.003s\r\n[2019-06-08 13:42:12,632] DEBUG    Site:1zeroR..GvJs Peers saved in 0.000s\r\n[2019-06-08 13:42:12,639] DEBUG    Db:Chart Commited in 0.007s (reason: Closing)\r\n[2019-06-08 13:42:12,654] DEBUG    Db:Chart C:/Tools/ZeroNet-win-dist-win64/data/chart.db closed in 0.022s, opened: 8\r\n[2019-06-08 13:42:12,663] DEBUG    Db:ContentDb Commited in 0.009s (reason: Closing)\r\n[2019-06-08 13:42:12,682] DEBUG    Db:ContentDb C:/Tools/ZeroNet-win-dist-win64/data/content.db closed in 0.028s, opened: 7\r\n[2019-06-08 13:42:12,683] DEBUG    Db:ZeroMe Commited in 0.000s (reason: Closing)\r\n[2019-06-08 13:42:12,707] DEBUG    Db:ZeroMe C:/Tools/ZeroNet-win-dist-win64/data/1MeFqFfFFGQfa1J3gJyYYUvb5Lksczq7nH/merged-ZeroMe/ZeroMe.db closed in 0.024s, opened: 6\r\n[2019-06-08 13:42:12,707] DEBUG    Db:ZeroBlog Commited in 0.000s (reason: Closing)\r\n[2019-06-08 13:42:12,726] DEBUG    Db:ZeroBlog C:/Tools/ZeroNet-win-dist-win64/data/1Gif7PqWTzVWDQ42Mo7np3zXmGAo3DXc7h/data/zeroblog.db closed in 0.019s, opened: 5\r\n[2019-06-08 13:42:12,726] DEBUG    Db:ZeroBlog Commited in 0.000s (reason: Closing)\r\n[2019-06-08 13:42:12,727] DEBUG    Db:ZeroBlog C:/Tools/ZeroNet-win-dist-win64/data/1BLoGBTid3NhGu8ts3fAfHJprnbrH3wfTV/data/zeroblog.db closed in 0.001s, opened: 4\r\n[2019-06-08 13:42:12,727] DEBUG    Db:ZeroBlog Commited in 0.000s (reason: Closing)\r\n[2019-06-08 13:42:12,729] DEBUG    Db:ZeroBlog C:/Tools/ZeroNet-win-dist-win64/data/1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8/data/zeroblog.db closed in 0.002s, opened: 3\r\n[2019-06-08 13:42:12,729] DEBUG    Db:ZeroBlog Commited in 0.000s (reason: Closing)\r\n[2019-06-08 13:42:12,730] DEBUG    Db:ZeroBlog C:/Tools/ZeroNet-win-dist-win64/data/1CpGZyfbUBBV5uXUoY653wVoqZFRojbEzd/data/zeroblog.db closed in 0.001s, opened: 2\r\n[2019-06-08 13:42:12,730] DEBUG    Db:ZeroTalk Commited in 0.000s (reason: Closing)\r\n[2019-06-08 13:42:12,731] DEBUG    Db:ZeroTalk C:/Tools/ZeroNet-win-dist-win64/data/1F4WVHDpQYxuJL6xEY3EZTYkZds9TTjVHC/data/users/zerotalk.db closed in 0.001s, opened: 1\r\n[2019-06-08 13:42:12,731] DEBUG    Db:ZeroBlog Commited in 0.000s (reason: Closing)\r\n[2019-06-08 13:42:12,732] DEBUG    Db:ZeroBlog C:/Tools/ZeroNet-win-dist-win64/data/1zeroRvxd42DSWUETotiaa8k5a5mDGvJs/data/zeroblog.db closed in 0.001s, opened: 0\r\n[2019-06-08 13:42:12,742] DEBUG    TrackerStorage Saved in 0.010s\r\n```\r\n\r\n#### Expected Results:\r\n\r\n updated zeronet\r\n", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1559962299, "modified": 1560349404, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2044", "source_type": "github"}], "next_comment_id": 11, "comment": {"1604066504_mirrored_bitcoren_github": [{"comment_id": 1, "body": "Thanks, i open 43110 port on VPS NAT and all is working.", "added": 1524647148, "modified": 1524647167, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1404#issuecomment-384263123", "source_type": "github"}], "1604067166_mirrored_yurivict_github": [{"comment_id": 2, "body": "Try to add \"--ui_host localhost:43110\"", "added": 1550401076, "modified": 1550401076, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1904#issuecomment-464460420", "source_type": "github"}, {"comment_id": 3, "body": "You need to install docker-compose and run with the docker-compose.yml.  \r\nSample file:\r\n```\r\nversion: '3'\r\nservices:\r\n\r\n  proxy:\r\n    container_name: proxy.zites.cf\r\n    image: nofish/zeronet\r\n    restart: always\r\n    environment:\r\n      ENABLE_TOR: \"true\"\r\n    volumes:\r\n      - ./data:/root/data\r\n      - ./log:/root/log\r\n      - ./zeronet.conf:/root/zeronet.conf\r\n    ports:\r\n      - \"26552:26552\"\r\n      - \"127.0.0.1:43110:43110\"\r\n    command: \"sh -c ' ( [ -e /root/plugins/disabled-Multiuser ] && rm -rf /root/plugins/Multiuser && mv /root/plugins/disabled-Multiuser /root/plugins/Multiuser ) && (/usr/bin/tor &) && python zeronet.py --ui_host proxy.zites.cf 127.0.0.1:43110 --ui_ip 0.0.0.0 --fileserver_port 26552'\"\r\n```", "added": 1550488845, "modified": 1550488845, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1904#issuecomment-464748094", "source_type": "github"}], "1604067230_mirrored_bitcoren_github": [{"comment_id": 4, "body": "Yes, at first I downloaded the site in the browser.", "added": 1554932293, "modified": 1554932293, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1979#issuecomment-481921782", "source_type": "github"}, {"comment_id": 5, "body": "```\r\nbitcoren@name:~/ZeroNet-py3$ python3 zeronet.py siteCmd 1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D siteList\r\n- Starting ZeroNet...\r\n- Libsecpk256k1 loaded\r\n- Version: 0.7.0 r4056, Python 3.6.7 (default, Oct 22 2018, 11:32:17) \r\n[GCC 8.2.0], Gevent: 1.4.0\r\nFileServer IPv6 not supported: [Errno 101] Network is unreachable\r\n- Unhandled exception: Expecting value: line 1 column 1 (char 0)\r\nTraceback (most recent call last):\r\n  File \"zeronet.py\", line 23, in main\r\n    main.start()\r\n  File \"/home/bitcoren/ZeroNet-py3/src/main.py\", line 515, in start\r\n    actions.call(config.action, action_kwargs)\r\n  File \"/home/bitcoren/ZeroNet-py3/src/main.py\", line 111, in call\r\n    back = func(**kwargs)\r\n  File \"/home/bitcoren/ZeroNet-py3/src/main.py\", line 333, in siteCmd\r\n    res = json.loads(ws.recv())\r\n  File \"/usr/lib/python3.6/json/__init__.py\", line 354, in loads\r\n    return _default_decoder.decode(s)\r\n  File \"/usr/lib/python3.6/json/decoder.py\", line 339, in decode\r\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\r\n  File \"/usr/lib/python3.6/json/decoder.py\", line 357, in raw_decode\r\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\r\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\r\n```", "added": 1554932870, "modified": 1554932870, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1979#issuecomment-481923413", "source_type": "github"}, {"comment_id": 6, "body": "```\r\n[2019-04-11 04:01:12,299] DEBUG    Site:1HeLLo..Tf3D Need connections: 6, Current: 8, Total: 672\r\n[2019-04-11 04:01:13,305] DEBUG    Site:1KoLHo..Sa6m Need connections: 1, Current: 1, Total: 1\r\n[2019-04-11 04:01:13,308] DEBUG    ConnServer Conn#91 204.44.72.141 [?] > Connecting... (site: None)\r\n[2019-04-11 04:01:14,192] DEBUG    ConnServer Conn#91 204.44.72.141 [v2] > Closing connection: Removing, waiting_requests: 0, sites: 1, buff: 0...\r\n[2019-04-11 04:01:14,195] DEBUG    Site:1KoLHo..Sa6m Tracker announce result: zero://204.44.72.141:10398 (sites: 4, new peers: 0, add: ['ipv4']) in 0.887s\r\n[2019-04-11 04:01:14,310] DEBUG    Site:1Name2..hM9F Need connections: 6, Current: 6, Total: 741\r\n[2019-04-11 04:01:15,315] DEBUG    Site:1uPDaT..NACf Need connections: 3, Current: 4, Total: 14\r\n[2019-04-11 04:01:15,419] WARNING  Site:1uPDaT..NACf Tracker http://open.acgnxtracker.com:80/announce announce failed: ConnectionResetError: [Errno 104] Connection reset by peer in SiteAnnouncer.py line 214 > SiteAnnouncer.py line 349 > Sit$\r\n[2019-04-11 04:01:15,420] DEBUG    Site:1uPDaT..NACf Tracker failed, skipping to next one...\r\n[2019-04-11 04:01:16,319] DEBUG    ConnServer Site announce tracker done in 4.021s, sleeping for 129.313s...\r\n[2019-04-11 04:01:24,996] DEBUG    ChartCollector Global collectors done in 0.004s\r\n[2019-04-11 04:01:24,998] DEBUG    ChartCollector Global collectors inserted in 0.001s\r\n[2019-04-11 04:01:35,271] DEBUG    Ui.UiServer 127.0.0.1 - - [2019-04-11 04:01:35] \"GET /Websocket?wrapper_key=27385e594c2d4a559d8600aef95c74bdc0c33b89a151cd604b47cf5156f34620 HTTP/1.1\" 101 129 0.002576\r\n\r\n```", "added": 1554933966, "modified": 1554934078, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1979#issuecomment-481926712", "source_type": "github"}, {"comment_id": 7, "body": "```\r\n[2019-04-11 17:08:47,186] INFO     Site:1KoLHo..Sa6m Publishing content.json to 5/1 peers (connected: 1) diffs: [] (0.00k)...\r\n[2019-04-11 17:08:47,201] DEBUG    Ui.UiServer 127.0.0.1 - - [2019-04-11 17:08:47] \"GET /Websocket?wrapper_key=1c6862ed7cb7afa258f801b207085f5626a45829d2a3edb0895f8ebacd32ad30 HTTP/1.1\" 101 129 0.047000\r\n[2019-04-11 17:08:47,295] DEBUG    Site:1KoLHo..Sa6m Websocket send error: WebSocketError: Socket is dead in UiWebsocket.py line 214 > websocket.py line 352\r\n[2019-04-11 17:08:47,295] INFO     Site:1KoLHo..Sa6m [OK] 194.1.237.140:13216: Thanks, file content.json updated! 1/5\r\n[2019-04-11 17:08:47,295] DEBUG    RateLimit Added to queue (15.00s left): 49 update 1KoLHoz1nSddbuf6HbfP19F7Ht7xNBSa6m content.json \r\n[2019-04-11 17:08:47,311] INFO     Site:1KoLHo..Sa6m Published content.json to 1 peers, publishing to 5 more peers in the background\r\n[2019-04-11 17:08:47,311] DEBUG    Site:1KoLHo..Sa6m Websocket send error: WebSocketError: Socket is dead in UiWebsocket.py line 214 > websocket.py line 352\r\n[2019-04-11 17:08:47,311] DEBUG    Site:1KoLHo..Sa6m Websocket send error: WebSocketError: Socket is dead in UiWebsocket.py line 214 > websocket.py line 352\r\n[2019-04-11 17:09:02,323] DEBUG    RateLimit Calling: 49 update 1KoLHoz1nSddbuf6HbfP19F7Ht7xNBSa6m content.json\r\n[2019-04-11 17:09:43,344] DEBUG    ConnServer Conn#55 77.249.123.145 [v2] > Closing connection: MessageLoop ended (closed: False), waiting_requests: 0, sites: 1, buff: 0...\r\n```", "added": 1554963320, "modified": 1554963320, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1979#issuecomment-482035873", "source_type": "github"}, {"comment_id": 8, "body": "```\r\nbitcoren@name:~/ZeroNet-py3$ python3 zeronet.py --silent siteCmd 1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D siteList\r\nFileServer IPv6 not supported: [Errno 101] Network is unreachable\r\n{'error': 'Invalid result: Expecting value: line 1 column 1 (char 0)', 'res_raw': ''}\r\n\r\n\r\nbitcoren@name:~/ZeroNet-py3$ python3 zeronet.py siteCmd 1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D siteList\r\n- Starting ZeroNet...\r\n- Libsecpk256k1 loaded\r\n- Version: 0.7.0 r4057, Python 3.6.7 (default, Oct 22 2018, 11:32:17) \r\n[GCC 8.2.0], Gevent: 1.4.0\r\nFileServer IPv6 not supported: [Errno 101] Network is unreachable\r\n- Unhandled exception: [Errno 32] Broken pipe\r\nTraceback (most recent call last):\r\n  File \"zeronet.py\", line 23, in main\r\n    main.start()\r\n  File \"/home/bitcoren/ZeroNet-py3/src/main.py\", line 520, in start\r\n    actions.call(config.action, action_kwargs)\r\n  File \"/home/bitcoren/ZeroNet-py3/src/main.py\", line 111, in call\r\n    back = func(**kwargs)\r\n  File \"/home/bitcoren/ZeroNet-py3/src/main.py\", line 333, in siteCmd\r\n    res_raw = ws.recv()\r\n  File \"/usr/local/lib/python3.6/dist-packages/websocket/_core.py\", line 313, in recv\r\n    opcode, data = self.recv_data()\r\n  File \"/usr/local/lib/python3.6/dist-packages/websocket/_core.py\", line 330, in recv_data\r\n    opcode, frame = self.recv_data_frame(control_frame)\r\n  File \"/usr/local/lib/python3.6/dist-packages/websocket/_core.py\", line 357, in recv_data_frame\r\n    self.send_close()\r\n  File \"/usr/local/lib/python3.6/dist-packages/websocket/_core.py\", line 390, in send_close\r\n    self.send(struct.pack('!H', status) + reason, ABNF.OPCODE_CLOSE)\r\n  File \"/usr/local/lib/python3.6/dist-packages/websocket/_core.py\", line 253, in send\r\n    return self.send_frame(frame)\r\n  File \"/usr/local/lib/python3.6/dist-packages/websocket/_core.py\", line 278, in send_frame\r\n    l = self._send(data)\r\n  File \"/usr/local/lib/python3.6/dist-packages/websocket/_core.py\", line 448, in _send\r\n    return send(self.sock, data)\r\n  File \"/usr/local/lib/python3.6/dist-packages/websocket/_socket.py\", line 157, in send\r\n    return _send()\r\n  File \"/usr/local/lib/python3.6/dist-packages/websocket/_socket.py\", line 139, in _send\r\n    return sock.send(data)\r\n  File \"/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py\", line 439, in send\r\n    return _socket.socket.send(self._sock, data, flags)\r\nBrokenPipeError: [Errno 32] Broken pipe\r\n```\r\n```\r\n[2019-04-11 19:50:15,579] DEBUG    Ui.UiServer 127.0.0.1 - - [2019-04-11 19:50:15] \"GET / HTTP/1.1\" 200 4417 0.002488\r\n[2019-04-11 19:50:34,924] DEBUG    Ui.UiServer 127.0.0.1 - - [2019-04-11 19:50:34] \"GET /Websocket?wrapper_key=e5b074bdf2fb3b760ebd024bdfd29edb6456b35e3f562c$\r\n[2019-04-11 19:50:52,656] DEBUG    ChartCollector Global collectors done in 0.004s\r\n[2019-04-11 19:50:52,658] DEBUG    ChartCollector Global collectors inserted in 0.001s\r\n[2019-04-11 19:51:02,731] DEBUG    Ui.UiServer 127.0.0.1 - - [2019-04-11 19:51:02] \"GET /Websocket?wrapper_key=27385e594c2d4a559d8600aef95c74bdc0c33b89a151cd$\r\n[2019-04-11 19:51:13,539] DEBUG    BroadcastServer Sending discover request (force: False)\r\n[2019-04-11 19:51:13,544] DEBUG    ConnServer Conn#131 178.170.68.153 [?] > Connecting... (site: None)\r\n[2019-04-11 19:51:13,549] DEBUG    BroadcastServer Broadcast using ips ['194.1.237.140'] on port 1544: discoverRequest\r\n[2019-04-11 19:51:13,550] DEBUG    BroadcastServer Got from ('194.1.237.140', 37561): discoverRequest\r\n[2019-04-11 19:51:13,849] DEBUG    ConnServer Conn#131 178.170.68.153 [v2] > Closing connection: Removing, waiting_requests: 0, sites: 1, buff: 0...\r\n[2019-04-11 19:51:13,850] DEBUG    Site:1HeLLo..Tf3D Tracker announce result: zero://178.170.68.153:17127 (sites: 4, new peers: 0, add: ['ipv4']) in 0.306s\r\n[2019-04-11 19:51:14,554] DEBUG    Site:1KoLHo..Sa6m Need connections: 2, Current: 2, Total: 2\r\n[2019-04-11 19:51:15,561] DEBUG    Site:1Name2..hM9F Need connections: 6, Current: 7, Total: 520\r\n[2019-04-11 19:51:16,568] DEBUG    Site:1uPDaT..NACf Need connections: 3, Current: 3, Total: 25\r\n[2019-04-11 19:51:17,573] DEBUG    ConnServer Site announce tracker done in 4.035s, sleeping for 129.298s...\r\n[2019-04-11 19:52:52,533] DEBUG    Db:ContentDb Optional size: 0.0MB/2200.7MB, Need delete: -2200.7MB\r\n[2019-04-11 19:52:53,083] DEBUG    SiteManager Saved sites in 0.02s (generate: 0.00s, write: 0.02s)\r\n[2019-04-11 19:52:53,084] DEBUG    SiteManager Updated merger sites in 0.000s\r\n[2019-04-11 19:53:26,880] DEBUG    ConnServer Conn#132 185.142.236.207 [?] > Connecting... (site: None)\r\n[2019-04-11 19:53:27,163] DEBUG    ConnServer Conn#132 185.142.236.207 [v2] > Closing connection: Removing, waiting_requests: 0, sites: 1, buff: 0...\r\n[2019-04-11 19:53:27,164] DEBUG    Site:1HeLLo..Tf3D Tracker announce result: zero://185.142.236.207:10443 (sites: 4, new peers: 0, add: ['ipv4']) in 0.284s\r\n[2019-04-11 19:53:27,880] DEBUG    Site:1KoLHo..Sa6m Need connections: 3, Current: 2, Total: 3\r\n[2019-04-11 19:53:27,880] DEBUG    ConnServer Conn#133 194.1.237.140 [?] > Connecting... (site: Site 1KoLHo..Sa6m)\r\n[2019-04-11 19:53:27,885] DEBUG    ConnServer Conn#133 194.1.237.140 [?] > Closing connection: 194.1.237.140 Connect error: ConnectionRefusedError: [Errno 11$\r\n[2019-04-11 19:53:27,886] DEBUG    Site:1KoLHo..Sa6m Connected before: 2, after: 2. Check site: True.\r\n[2019-04-11 19:53:28,887] DEBUG    Site:1Name2..hM9F Need connections: 6, Current: 7, Total: 524\r\n[2019-04-11 19:53:29,893] DEBUG    Site:1uPDaT..NACf Need connections: 3, Current: 3, Total: 25\r\n[2019-04-11 19:53:30,900] DEBUG    ConnServer Site announce tracker done in 4.023s, sleeping for 129.311s...\r\n```\r\nsiteList should return a list of sites.\r\nWhy doesn't the command do this?", "added": 1554991328, "modified": 1554991328, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1979#issuecomment-482202168", "source_type": "github"}, {"comment_id": 9, "body": "I renamed the plugin UiPassword to disabled-UiPassword and everything works.\r\nPlease make local commands to work with UiPassword.\r\nMany thanks for the support.", "added": 1555069547, "modified": 1555069839, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1979#issuecomment-482601661", "source_type": "github"}, {"comment_id": 10, "body": "siteCmd command did not work in version 4080 with \"UiPassword\" again\r\n```\r\nbitcoren@ubuntu:/hdd/ZeroNet-py3$ python3 zeronet.py siteCmd 1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D siteList\r\n- Starting ZeroNet...\r\n- Libsecpk256k1 loaded\r\n- Version: 0.7.0 r4080, Python 3.6.7 (default, Oct 22 2018, 11:32:17) \r\n[GCC 8.2.0], Gevent: 1.4.0\r\nFileServer IPv6 not supported: [Errno 101] Network is unreachable\r\n- Connecting to ws://192.168.1.21:43110/Websocket?wrapper_key=becccc9b458bb3038d1d39b4d509f18dad0583a7d94cb9265ed24bb3aa2ab579\r\n- Unhandled exception: [Errno 32] Broken pipe\r\nTraceback (most recent call last):\r\n  File \"zeronet.py\", line 23, in main\r\n    main.start()\r\n  File \"/hdd/ZeroNet-py3/src/main.py\", line 529, in start\r\n    actions.call(config.action, action_kwargs)\r\n  File \"/hdd/ZeroNet-py3/src/main.py\", line 111, in call\r\n    back = func(**kwargs)\r\n  File \"/hdd/ZeroNet-py3/src/main.py\", line 338, in siteCmd\r\n    res_raw = ws.recv()\r\n  File \"/home/bitcoren/.local/lib/python3.6/site-packages/websocket/_core.py\", line 313, in recv\r\n    opcode, data = self.recv_data()\r\n  File \"/home/bitcoren/.local/lib/python3.6/site-packages/websocket/_core.py\", line 330, in recv_data\r\n    opcode, frame = self.recv_data_frame(control_frame)\r\n  File \"/home/bitcoren/.local/lib/python3.6/site-packages/websocket/_core.py\", line 357, in recv_data_frame\r\n    self.send_close()\r\n  File \"/home/bitcoren/.local/lib/python3.6/site-packages/websocket/_core.py\", line 390, in send_close\r\n    self.send(struct.pack('!H', status) + reason, ABNF.OPCODE_CLOSE)\r\n  File \"/home/bitcoren/.local/lib/python3.6/site-packages/websocket/_core.py\", line 253, in send\r\n    return self.send_frame(frame)\r\n  File \"/home/bitcoren/.local/lib/python3.6/site-packages/websocket/_core.py\", line 278, in send_frame\r\n    l = self._send(data)\r\n  File \"/home/bitcoren/.local/lib/python3.6/site-packages/websocket/_core.py\", line 448, in _send\r\n    return send(self.sock, data)\r\n  File \"/home/bitcoren/.local/lib/python3.6/site-packages/websocket/_socket.py\", line 157, in send\r\n    return _send()\r\n  File \"/home/bitcoren/.local/lib/python3.6/site-packages/websocket/_socket.py\", line 139, in _send\r\n    return sock.send(data)\r\n  File \"/home/bitcoren/.local/lib/python3.6/site-packages/gevent/_socket3.py\", line 439, in send\r\n    return _socket.socket.send(self._sock, data, flags)\r\nBrokenPipeError: [Errno 32] Broken pipe\r\n```\r\n", "added": 1556125969, "modified": 1556126057, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1979#issuecomment-486407322", "source_type": "github"}]}}